<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MANIFEST_DESC', "This page contains information about Lanius CMS, the people who brought you Lanius CMS with their development and credits to other software used inside Lanius CMS."); /* r1 */
define('_MANIFEST_MW', "Middleware"); /* r1 */
define('_ABOUT_TEAM', "The Lanius CMS Team"); /* r1 */
define('_ABOUT_TESTERS', "Testers"); /* r1 */
define('_ABOUT_AND_MANY_OTHERS', "and many others"); /* r1 */
define('_ABOUT_OTHER_DEV_CON', "Other developers, testers and contributors"); /* r1 */
?>