<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_CONTENT_NOTIFY_MSG', "%sA new content item has been added to %s by user %s (user ID #%d)\n\nTitle: %s\nSection: %\nCategory: %s\n\n%s"); /* r1, sprintf, raw */
define('_CONTENT_NOTIFY_SUBJ', "New content added to %s"); /* r1, sprintf, raw */
?>