<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_READ_MORE', "Read more..."); /* r1 */
define('_READ_MORE_REGISTER', "Register to read more..."); /* r1 */
define('_CONTENT_AUTO_FILL', "Auto-fill"); /* r1 */
define('_CONTENT_AUTO_META', "Automatically fill keywords and description fields if left blank"); /* r1 */
define('_CONTENT_BY', " by "); /* r1 */
define('_CONTENT_KEYWORDS', "Content META keywords:"); /* r1 */
define('_CONTENT_DESCRIPTION', "Content META description:"); /* r1 */
define('_E_WARNTITLE', "Content item must have a title"); /* r1 */
define('_E_WARNTEXT', "Content item must have at least intro text"); /* r1 */
define('_CONTENT_ARCHIVE', "Archive"); /* r170 */
define('_CONTENT_ARCHIVE_ALL_MONTHS', "All months"); /* r170 */
define('_ARCHIVE_SEARCH_FAILURE', "There are no archived entries for %s %s"); /* r1, sprintf */
define('_ARCHIVE_SEARCH_FAILURE_YEAR', "There are no archived entries for year %s"); /* r170, sprintf */
define('_ARCHIVE_SEARCH_SUCCESS', "These are the archived entries for %s %s"); /* r1, sprintf */
define('_ARCHIVE_SEARCH_SUCCESS_YEAR', "These are the archived entries for year %s"); /* r170, sprintf */
define('_CONTENT_TITLE_ALIAS', "Title alias"); /* r1 */
define('_CONTENT_PERMALINK_TO', "Permanent link to %s"); /* r170, sprintf */
define('_CONTENT_EXPORT_PDF', "Export to PDF"); /* r1 */
define('_CONTENT_SHOW_ON_FRONTPAGE', "Show on frontpage"); /* r1 */
define('_CONTENT_NO_EDITOR_ACCESS', "You have no editor access to any category"); /* r1 */
define('_EMAIL_ERR_NOINFO', "You must enter your valid email and a valid email to send to."); /* r1 */
define('_EMAIL_MSG', " The following page from the %s website has been sent to you by %s ( %s )\n\nYou can access it at the following URL: %s"); /* r1, sprintf */
define('_EMAIL_INFO', "Item sent by"); /* r1 */
define('_EMAIL_SENT', "This item has been sent to %s"); /* r1, sprintf */
define('_EMAIL_NOT_SENT', "There was an error sending this item to %s"); /* r1, sprintf */
define('_E_CONTENT', "Content"); /* r1 */
define('_E_INTRO', "Intro text"); /* r1 */
define('_E_MAIN', "Main text"); /* r1 */
define('_EMAIL_TITLE', "Email a friend"); /* r1 */
define('_EMAIL_FRIEND', "Email this to a friend."); /* r1 */
define('_EMAIL_FRIEND_ADDR', "Your friend's email:"); /* r1 */
define('_EMAIL_YOUR_NAME', "Your name:"); /* r1 */
define('_EMAIL_YOUR_MAIL', "Your email:"); /* r1 */
?>