<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DOWNLOADS_TITLE', "Downloads"); /* r1 */
define('_DOWNLOADS_DESC', " Here is a collection of files which might be of interest to you."); /* r1 */
define('_DOWNLOADS_WEBSITE', "Website"); /* r1 */
define('_DOWNLOADS_DOWNLOAD', "Download"); /* r1 */
define('_DOWNLOADS_INFO', "More info"); /* r1 */
define('_DOWNLOADS_ADDED', "Added on"); /* r1 */
define('_DOWNLOADS_FILESIZE', "File size"); /* r1 */
define('_DOWNLOADS_HITS', "Total downloads"); /* r1 */
define('_DOWNLOADS_MODIFIED', "Modified on"); /* r1 */
define('_DOWNLOADS_DESCRIPTION', "Description"); /* r1 */
define('_DOWNLOADS_ORDER_BY', "Order by"); /* r1 */
define('_DOWNLOADS_LATEST', "Latest"); /* r1 */
define('_DOWNLOADS_VIEW_AS', "View as"); /* r1 */
define('_DOWNLOADS_VIEW_LIST', "list"); /* r1 */
define('_DOWNLOADS_VIEW_TABLE', "table"); /* r1 */
define('_DOWNLOADS_SUBMIT_DESC', "Specify an URL from where to download the file or a file upload.\nIf you specify a file upload the URL will be ignored."); /* r1 */
define('_DOWNLOADS_FILE', "File"); /* r1 */
define('_SUBMIT_DOWNLOAD', "Submit a download"); /* r1 */
define('_DOWNLOADS_SUBMIT_TO_CATEGORY', "Submit a download to this category"); /* r1 */
define('_NOT_EXIST', "The page you are trying to access does not exist."); /* r1 */
define('_DOWNLOADS_GO_BACK_TO', "Go back to"); /* r1 */
define('_DOWNLOADS_CATEGORIES', "download categories"); /* r1 */
define('_DOWNLOADS_CHANGE_VIEW', "Change view"); /* r1 */
define('_DOWNLOADS_NA', "No downloads available"); /* r566 */
define('_DOWNLOADS_NC', "Please submit a valid url or upload a file"); /* r574 */
?>