<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DOWNLOADS_ADDED_SUBJECT', "New download submitted to %s"); /* r1, sprintf, raw */
define('_DOWNLOADS_ADDED_MAIL', "A new download has been submitted on %s by user %s (user id #%d), details follow.\n\nTitle: %s\nAuthor: %s\nDescription: %s\nFile size: %s"); /* r1, sprintf, raw */
?>