<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_EVENTS_IN', "Events in "); /* r1 */
define('_EVENT_EVENTS', "Events"); /* r1 */
define('_EVENTS_DESC', "The list below shows the events which will take place in this month."); /* r1 */
define('_EVENTS_TITLE', "Event title"); /* r1 */
define('_EVENTS_DATE', "Event dates"); /* r1 */
define('_EVENTS_TO', "To"); /* r1 */
define('_EVENTS_NONE', "No events this month"); /* r1 */
define('_EVENT_DATE_FORMAT', "%A, %d %B %Y %H:%M:%S"); /* r1, date */
define('_EVENT_ALL_MONTHS', "All months"); /* r1 */
define('_EVENT_NONE_YEAR', "No events this year"); /* r1 */
?>