<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FAQ_TITLE', "FAQs"); /* r1 */
define('_FAQ_FAQH', "Frequently Asked Questions"); /* r1 */
define('_FAQ_QUESTION', "Question:"); /* r1 */
define('_FAQ_ANSWER', "Answer:"); /* r1 */
define('_FAQ_QUESTIONS', "Questions"); /* r1 */
define('_FAQ_INDEX', "Back to index"); /* r1 */
define('_FAQ_SUBMIT', "Submit new FAQ"); /* r1 */
define('_FAQ_QANDA', "Question &amp; Answer"); /* r1 */
?>