<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FAQ_ADDED_SUBJECT', "New FAQ submitted to %s"); /* r1, sprintf, raw */
define('_FAQ_ADDED_BODY', "A new FAQ has been added to %s by user %s (user id #%d), details follow.\n\nQuestion: %s\n\nQuestioner's email address: %s"); /* r1, sprintf, raw */
?>