<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FB_DOUBLE_CLICK_BROWSE', "Double click to browse to"); /* r1 */
define('_FB_DOUBLE_CLICK_PREVIEW', "Double click to preview"); /* r1 */
define('_FB_NO_SELECTION', "No file selected"); /* r1 */
define('_FB_SELECTION', "Current selection"); /* r1 */
define('_FB_PREVIEW', "Preview"); /* r1 */
define('_FB_PUBLIC_NOTICE', "Note: you cannot delete uploaded files and they will be publicly accessible"); /* r1 */
define('_FB_CURRENT_SELECTION', "Current selection"); /* r1 */
?>