<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FORUM_REPORTED_POST', "Post reported to moderators in %s forum topic"); /* r1, sprintf */
define('_FORUM_REPORTED_POST_MSG', "A forum user has reported a post to moderators of forum category \"%s\"\n\nPost ID: %d %s\nPost subject: %s\nPost username: %s\nPost username ID: %s\n\nReporter username: %s\nReporter comment: %s\n\n"); /* r1, sprintf, raw */
define('_FORUM_POST_NOTIFICATION', "New post notification from %s forum topic"); /* r1, sprintf */
define('_FORUM_POST_NOTIFICATION_MSG', "A new post has been made to a topic to which you have subscribed on the %s forum\nSubject: '%s' in forum: '%s'\n\nPosted by: %s\n\nMessage:\n---\n%s\n\n---\nFull topic available at the following address:\n%s"); /* r1, sprintf, raw */
define('_FORUM_NEW_TOPIC_SUBJECT', "New topic notification from %s forum"); /* r1, sprintf */
define('_FORUM_NEW_TOPIC_MESSAGE', "A new topic has been created in the %s forum\n\nSubject: %s\nPosted by: %s (%s)\nMessage:\n---\n%s\n\n---\nFull topic available at the following address:\n%s"); /* r1, sprintf, raw */
?>