<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FORUM_TITLE', "Forum"); /* r1 */
define('_FORUM_TOPICS', "Topics"); /* r1 */
define('_FORUM_REPLIES', "Replies"); /* r1 */
define('_FORUM_LAST', "Last reply"); /* r1 */
define('_FORUM_VIEWS', "Views"); /* r1 */
define('_FORUM_VIEW', "View post"); /* r1 */
define('_FORUM_POSTS', "Posts:"); /* r1 */
define('_FORUM_MEMBER_SINCE', "Member since"); /* r1 */
define('_FORUM_NEW', "New posts"); /* r1 */
define('_FORUM_OLD', "Old posts"); /* r1 */
define('_FORUM_TOTAL', "Total"); /* r1 */
define('_FORUM_NAME', "Name:"); /* r1 */
define('_FORUM_SUBJECT', "Subject:"); /* r1 */
define('_FORUM_MESSAGE', "Message:"); /* r1 */
define('_FORUM_PREVIEW', "Preview"); /* r1 */
define('_FORUM_POST_NEW', "Post new topic in &quot;%s&quot;"); /* r1, sprintf */
define('_FORUM_POST_REP', "Post reply to &quot;%s&quot;"); /* r1, sprintf */
define('_FORUM_REVIEW', "Review"); /* r1 */
define('_FORUM_POST_NONE', "No posts"); /* r1 */
define('_FORUM_REPLY_NONE', "No replies"); /* r1 */
define('_FORUM_POST_TOPIC', "Post topic"); /* r1 */
define('_FORUM_MSG_REPORTED', "Forum moderators will shortly receive a notifcation about your report"); /* r1 */
define('_FORUM_NEW_TOPIC', "New topic"); /* r1 */
define('_FORUM_POST_REPLY', "Post reply"); /* r1 */
define('_FORUM_POST_EDIT', "Edit post"); /* r1 */
define('_FORUM_BY', "by"); /* r1 */
define('_FORUM_TOP', "Top"); /* r1 */
define('_FORUM_DATE_FORMAT_LC', "%d %B %Y %H:%M"); /* r1, sprintf */
define('_FORUM_INDEX', "Index"); /* r1 */
define('_FORUM_LATEST', "Latest posts"); /* r1 */
define('_FORUM_SEARCH', "Search"); /* r1 */
define('_FORUM_CODE', "Code"); /* r1 */
define('_FORUM_REPLY', "Reply"); /* r1 */
define('_FORUM_QUOTE', "Quote"); /* r1 */
define('_FORUM_QUOTE_BY', "Quote by %s"); /* r1, sprintf */
define('_FORUM_BACK', "Back"); /* r1 */
define('_FORUM_EDIT', "Edit"); /* r1 */
define('_FORUM_JUMP', "Jump to ..."); /* r1 */
define('_FORUM_NOTIFY_NOT_LOGGED_IN', "You could receive email notifications if you were logged in"); /* r1 */
define('_FORUM_NOTIFY_SEND', "Send email notifications of replies to this topic"); /* r1 */
define('_FORUM_NOTIFY_ENABLE', "Enable email notification"); /* r1 */
define('_FORUM_NOTIFY_DISABLE', "Disable email notification"); /* r1 */
define('_FORUM_USER_PROFILE', "Forum user profile of %s"); /* r1, sprintf */
define('_FORUM_MEMBER_LOCATION', "Location"); /* r1 */
define('_FORUM_MEMBER_WEBSITE', "Website"); /* r1 */
define('_FORUM_MEMBER_INFORMATION', "User provided information (max %d characters)"); /* r1, sprintf */
define('_FORUM_MEMBER_SIGNATURE', "Custom signature (max %d characters)"); /* r1, sprintf */
define('_FORUM_EDIT_PROFILE', "Edit forum user profile of %s"); /* r1, sprintf */
define('_FORUM_APPLY_PROFILE_CHANGES', "Apply changes"); /* r1 */
define('_FORUM_REPORT_TO_MODERATORS', "Report to moderators"); /* r1 */
define('_FORUM_REPORT_TO_MODERATORS_DESC', "Use this function to inform the moderators and administrators of an abusive or wrongly posted message."); /* r1 */
define('_FORUM_REPORT_COMMENT', "Enter comment"); /* r1 */
define('_FORUM_CURRENT_AVATAR', "&lt; Current &gt;"); /* r1 */
define('_FORUM_JS_ENTER_NAME', "You should enter a name"); /* r1 */
define('_FORUM_JS_ENTER_SUBJECT', "You must enter a subject"); /* r1 */
define('_FORUM_JS_ENTER_MESSAGE', "You must enter a message"); /* r1 */
define('_FORUM_DELETE_CONFIRM', "Are you sure to want to delete this post?"); /* r1 */
define('_FORUM_FILTER_RE_PREFIX', "Prefix used in replies"); /* r1 */
define('_FORUM_UNREAD_POSTS', "View new posts"); /* r1 */
define('_FORUM_NEW_POSTS', "New posts"); /* r1 */
define('_FORUM_VIEW_ALL_USER_POSTS', "View all posts of this user"); /* r1 */
define('_FORUM_VIEW_USER_POSTS_LIST', "View all posts of user %s"); /* r1, sprintf */
define('_FORUM_DELETE_THREAD', "Delete whole thread"); /* r1 */
define('_FORUM_MOVE', "Move..."); /* r1 */
define('_FORUM_LOCK', "Lock"); /* r1 */
define('_FORUM_UNLOCK', "Unlock"); /* r1 */
define('_FORUM_STICK', "Stick"); /* r1 */
define('_FORUM_UNSTICK', "Unstick"); /* r1 */
define('_FORUM_MOVE_THREAD', "Move thread"); /* r1 */
define('_FORUM_MOVE_THREAD_DESC', "Move a thread into another forum category"); /* r1 */
define('_FORUM_MOVE_INTO', "Move into"); /* r1 */
define('_FORUM_CANNOT_MOVE_SELF', "Cannot move thread into same category!"); /* r1 */
define('_FORUM_MOVE_NEW_SUBJECT', "Change subject to"); /* r1 */
define('_FORUM_USER_INFO', "Forum user information"); /* r638 */
define('_FORUM_USER_STATS', "Forum user statistics"); /* r638 */
define('_FORUM_INVALID_URL', "Invalid URL specified"); /* r364 */
?>