<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FRONTPAGE_ERROR', "Frontpage error"); /* r170 */
define('_FRONTPAGE_ERROR_NO_ITEM', "Frontpage error: there is no published content item in frontpage"); /* r170 */
?>