<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_GALLERY_TITLE', "Gallery"); /* r1 */
define('_GALLERY_GO_BACK_TO', "Go back to"); /* r1 */
define('_GALLERY_GALLERIES', "gallery categories"); /* r1 */
define('_GALLERY_SUBMIT_TO_CATEGORY', "Submit an image to this category"); /* r1 */
define('_GALLERY_FILE_WITH_EXT', "Valid file extensions are %s"); /* r1, sprintf */
define('_GALLERY_SUBMIT_DESC', "Specify an URL where the image is located or else a file upload.\nIf you specify a file upload the URL will be ignored."); /* r1 */
define('_GALLERY_SUBMIT_PICTURE', "Submit an image"); /* r1 */
?>