<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_GALLERY_ADDED_SUBJECT', "New gallery item added to %s"); /* r1, sprintf, raw */
define('_GALLERY_ADDED_MAIL', "A new gallery item has been added to %s by user %s (user ID #%d), details follow.\n\nTitle: %s\nURL (full): %s\nDescription: %s"); /* r1, sprintf, raw */
?>