<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_GUESTBOOK_TITLE', "Guestbook"); /* r1 */
define('_GUESTBOOK_VIEW', "View guestbook"); /* r1 */
define('_GUESTBOOK_SIGN', "Sign"); /* r1 */
define('_GUESTBOOK_TOTAL_ENTRIES', "Total number of entries: "); /* r1 */
define('_GUESTBOOK_VIEWS_PAGE', "Number of entries per page:"); /* r1 */
define('_GUESTBOOK_COMMENTS', "Comments"); /* r1 */
define('_GUESTBOOK_POSTED', "Posted at"); /* r1 */
define('_GUESTBOOK_NAME', "Name"); /* r1 */
define('_GUESTBOOK_HOMEPAGE', "Homepage"); /* r1 */
define('_GUESTBOOK_COUNTRY', "Country"); /* r1 */
define('_GUESTBOOK_HEADLINE', "Headline"); /* r1 */
define('_GUESTBOOK_MESSAGE', "Message"); /* r1 */
define('_GUESTBOOK_REQUIRED', "These fields are required"); /* r1 */
define('_GUESTBOOK_HTML_DIS', "**HTML is disabled"); /* r1 */
define('_GUESTBOOK_REPLY', "Reply"); /* r1 */
define('_GUESTBOOK_PREV', "Previous 10"); /* r1 */
define('_GUESTBOOK_INVALID_EMAIL', "The email address you entered is not valid"); /* r1 */
define('_GUESTBOOK_DOUBLE_SIGN', "You have already submitted an entry"); /* r1 */
?>