<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_USER_LOGIN', "User login"); /* r1 */
define('_USER_AUTHENTICATED', "Welcome back %s, you are authenticated as %s."); /* r1, sprintf */
define('_USER_WELCOME_BACK', "Welcome back %s"); /* r170, sprintf */
define('_USER_EDIT_PROFILE', "Edit user profile"); /* r905 */
?>