<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MESSAGE_ATTACH', "Attachment: "); /* r1 */
define('_CONTACT_ATTACH_TOOBIG', "Attachment size is too big"); /* r1 */
define('_THANK_MESSAGE', "Thank you for your message."); /* r422 */
define('_MESSAGE_TITLE', "Send message"); /* r1 */
define('_MESSAGE_PROMPT', " Enter your message:"); /* r1 */
define('_CONTACT_TELEPHONE', "Telephone: "); /* r1 */
define('_CONTACT_MOBILE', "Mobile: "); /* r1 */
define('_CONTACT_FAX', "Fax: "); /* r1 */
define('_CONTACT_POSITION', "Position: "); /* r1 */
define('_CONTACT_ADDRESS', "Address: "); /* r1 */
define('_CONTACT_MISC', "Information: "); /* r1 */
define('_MESSAGE_RECIPIENTS', "Recipients"); /* r423 */
define('_MESSAGE_NO_RECIPIENTS', "No user is available as recipient"); /* r423 */
define('_MESSAGE_INVALID_RECIPIENT', "Specified recipient has not allowed receiving messages"); /* r452 */
define('_MESSAGE_RECIPIENT_NO_ATTACH', "Selected recipient does not allow attachments"); /* r423 */
define('_MESSAGE_NOTIFY_CONTENT_FULL', "Message:\n---\n%s\n\n---"); /* r423, sprintf, raw */
define('_MESSAGE_NOTIFY_CONTENT_URL', "Full message available at the following address:\n\n%s"); /* r423, sprintf, raw */
define('_MESSAGE_BROKEN_CFG', "Cannot send messages because storage mode and email delivery are both deactivated"); /* r894 */
define('_MESSAGE_SEND_PM', "Send PM"); /* r535 */
define('_MESSAGE_EMAIL_HIDDEN', "concealed for other users"); /* r542 */
define('_MESSAGE_FULL_DELIVERY_NOTICE', "Your message will be delivered via email, therefore your email address will be visible in the message From address"); /* r842 */
?>
