<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MESSAGE_NOTIFY', "New message notification from %s"); /* r423, sprintf */
define('_MESSAGE_NOTIFY_BODY', "You have received a new message at %s.\nSent by: %s\nSubject: '%s'\n%s"); /* r423, sprintf, raw */
?>