<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_NO_SELECTION', "No selection has been made, please try again"); /* r1 */
define('_POLLS_HEAD', "Manage polls"); /* r1 */
define('_POLLS_OPTIONS', "# of options"); /* r1 */
define('_POLLS_QUESTION', "Poll question"); /* r1 */
define('_POLLS_TITLE', "Poll - results"); /* r1 */
define('_SURVEY_TITLE', "Poll title:"); /* r1 */
define('_NUM_VOTERS', "Number of voters"); /* r1 */
define('_FIRST_VOTE', "First vote"); /* r1 */
define('_LAST_VOTE', "Last vote"); /* r1 */
define('_SEL_POLL', "Select poll"); /* r1 */
define('_NO_RESULTS', "There are no results for this poll."); /* r1 */
define('_SEL_POLL_LIST', "Select poll from the list"); /* r1 */
?>