<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_PROMPT_PASSWORD', "Lost your password?"); /* r1 */
define('_NEW_PASS_DESC', "Please enter your username and email address then click on the Send Password button. \nYou will shortly receive a new password which you could use to login."); /* r1 */
define('_BUTTON_SEND_PASS', "Send password"); /* r1 */
define('_REGISTER_TITLE', "Registration"); /* r1 */
define('_REGISTER_VPASS', "Verify password:"); /* r1 */
define('_REGISTER_REQUIRED', "always required fields"); /* r170 */
define('_REGISTER_XUP_REQUIRED', "required fields if not uploading a XUP descriptor"); /* r170 */
define('_BUTTON_SEND_REG', "Send registration"); /* r1 */
define('_SENDING_PASSWORD', "The password you have specified will be sent to the above mentioned email address."); /* r170 */
define('_SENDING_NEW_PASSWORD', "A password will be automatically generated and sent to your email address.\nOnce you have received your new password you can login in and change it."); /* r170 */
define('_SENDING_ACTIVATION', "A link with an activation code will be sent to your email address.\nOnce you have activated your account you will be able to enter your password."); /* r170 */
define('_ERROR_PASS', "Sorry, no corresponding user was found."); /* r1 */
define('_NEWPASS_SENT', "Operation completed.\nIf you have specified the correct account information, you will shortly receive details via email."); /* r170 */
define('_REGWARN_NAME', "Please enter your name."); /* r1 */
define('_REGWARN_UNAME', "Please enter a username."); /* r1 */
define('_REGWARN_MAIL', "Please enter a valid email address."); /* r1 */
define('_REGWARN_PASS', "Please enter a valid password.  No spaces, more than 6 characters and contain 0-9,a-z,A-Z"); /* r1 */
define('_REGWARN_VPASS1', "Please verify the password."); /* r1 */
define('_REGWARN_VPASS2', "Password and verification do not match, please try again."); /* r1 */
define('_REGISTRATION_COMPLETE', "Registration complete!"); /* r1 */
define('_REGISTRATION_ACTIVATION_SUCCESS', "User account activation completed successfully!"); /* r170 */
define('_REGISTRATION_INVALID_ACTIVATION', "Invalid activation code or wrong email address!"); /* r170 */
define('_REGISTRATION_CAN_LOGIN', "You may now login using the account details you specified."); /* r170 */
define('_REGISTRATION_CAN_LOGIN_PW', "A reminder email with the account details you specified has been sent to the email address you provided."); /* r170 */
define('_REGISTRATION_CAN_LOGIN_NPW', "A reminder email with your username and a generated password has been sent to the email address you provided."); /* r170 */
define('_REGISTRATION_NOT_CAN_LOGIN', "Your account has been created and is pending activation by administrator."); /* r170 */
define('_REGISTRATION_MAY_LOGIN', "You may now login at this address:\n%s"); /* r643, sprintf, raw */
define('_REGISTRATION_MAY_NOT_LOGIN', "Your account is pending activation, once activated you will be able to login at this address:\n%s'"); /* r643, sprintf, raw */
define('_REGISTRATION_COMPLETE_ACTIVATE', "Your account has been created and the activation link has been sent to the email address you provided. Note that you must activate the account by clicking on the activation link when you get the email before you can login."); /* r1 */
define('_REGISTRATION_ACTIVATION_RESENT', "The activation link for your account has been sent again to the email address you provided."); /* r170 */
define('_REGISTRATION_XUP_SUPPORT', "Enable XUP support"); /* r1 */
define('_REGISTRATION_XUP_DESCRIPTION', "If you upload your XUP descriptor (%s) you will eventually need to specify only the password and the verification code (if active)"); /* r1, sprintf */
define('_REGISTRATION_ACTIVATION_RESEND_MSG', "If you have not yet received the activation code, %sclick here%s to proceed to send it again."); /* r170, sprintf */
define('_REGISTRATION_XUP_READ_MORE', "read more about XUP"); /* r1 */
define('_REGISTRATION_XUP_FILENAME', "Upload your XUP file"); /* r1 */
define('_REGISTRATION_ACTIVATION', "User account activation"); /* r170 */
define('_REGISTRATION_ACTIVATION_CODE', "Activation Code"); /* r170 */
define('_REGISTRATION_ACTIVATE', "Activate"); /* r170 */
define('_REGISTRATION_RESEND', "Re-send"); /* r170 */
define('_REGISTRATION_ACTIVATION_DESC', "Please enter the email address associated to your account and the activation code you received through it."); /* r170 */
define('_REGISTRATION_ACTIVATION_RESEND_DESC', "Please enter the email address associated to your account and the activation code will be sent again to you."); /* r170 */
define('_REGISTRATION_DISABLED', "New user registrations are currently disabled"); /* r642 */
?>