<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_REGISTRATION_NEWPASS_MSG', "The user account %s has this email associated with it.\nA web user has requested that a new password be sent.\n\nYour new password is: %s\n\nIf you didn't ask for this, don't worry. You are seeing this message, not them.\n\nIf this was an error just login with your new password and then change your password to what you would like it to be.\n\n"); /* r1, sprintf, raw */
define('_REGISTRATION_NEWPASS_SUBJ', "New password for %s at %s"); /* r1, sprintf, raw */
define('_REGISTRATION_OLDPASS_SUBJ', "Account details for %s at %s"); /* r170, sprintf, raw */
define('_REGISTRATION_ACTIVATION_SUBJ', "Account activation for %s at %s"); /* r170, sprintf, raw */
define('_USEND_MSG_ACTIVATE', "Hello %s,\n\nThank you for registering at %s. Your account is created and must be activated before you can use it.\nTo activate the account click on the following link or copy-paste it in your browser:\n\n%s\n\nYou can also access directly %s and use the following Activation Code:\n\n%s\n\nAfter activation you will be prompted to choose a password and may login using the following username:\n%s\n"); /* r170, sprintf, raw */
define('_USEND_MSG', "Hello %s,\n\nThank you for registering at %s.\n\nThese are the account credentials defined for you:\nUsername: %s\nPassword: %s\n\n%s"); /* r1, sprintf, raw */
define('_USEND_MSG_NTY', "Hello %s,\n\nThese are the account credentials defined for you:\nUsername: %s\nPassword: %s\n\nYou may login at this address:\n%s"); /* r1, sprintf, raw */
define('_USEND_MSG_NOPASS', "Hello %s,\n\nYou have been added to %s as a user.\n%s"); /* r1, sprintf, raw */
define('_REGISTRATION_NOTIFY_SUBJECT', "New user registered at %s"); /* r1, sprintf, raw */
define('_REGISTRATION_NOTIFY_MAIL', "A new user has registered at %s.\n\nUsername: %s\nUser ID: %d"); /* r1, sprintf, raw */
?>