<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SEARCH_TITLE', "Search"); /* r1 */
define('_PROMPT_KEYWORD', "Search keyword"); /* r1 */
define('_NUM_RESULTS', "returned %d matches"); /* r1, sprintf */
define('_SEARCH_NOKEYWORD', "No results were found"); /* r1 */
define('_SEARCH_IGNOREKEYWORD', "One or more common words were ignored in the search"); /* r1 */
define('_SEARCH_ANYWORDS', "Any words"); /* r1 */
define('_SEARCH_ALLWORDS', "All words"); /* r1 */
define('_SEARCH_PHRASE', "Exact phrase"); /* r1 */
define('_SEARCH_NEWEST', "Newest first"); /* r1 */
define('_SEARCH_OLDEST', "Oldest first"); /* r1 */
define('_SEARCH_POPULAR', "Most popular"); /* r1 */
define('_SEARCH_ALPHABETICAL', "Alphabetical"); /* r1 */
define('_SEARCH_CATEGORY', "Section/Category"); /* r1 */
define('_SEARCH_REDUNDANT_KEYWORDS', "Ignored redundant keywords"); /* r1 */
?>