<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_USER_TITLE', "User"); /* r1 */
define('_PASS_VERR1', "If changing your password please enter the password again to verify."); /* r1 */
define('_PASS_VERR2', "If changing your password please make sure the password and verification match."); /* r1 */
define('_USER_DETAILS_SAVE', "Your user details have been saved."); /* r1 */
define('_EDIT_TITLE', "Edit your user details"); /* r1 */
define('_USER_VPASS', "Verify Password:"); /* r1 */
define('_USER_CURRENT_PASS', "Current password"); /* r1 */
define('_USER_ORIG_PASS_MISMATCH', "Original password does not match!"); /* r1, raw */
define('_PASS_MATCH', "Passwords do not match!"); /* r1, raw */
define('_USER_WELCOME', "Welcome!"); /* r1 */
define('_USER_ALLOW_DELETE', "Allow remove profile from edit user profile"); /* r170 */
define('_USER_DELETE_PROFILE', "Remove profile"); /* r170 */
define('_USER_DELETE_PROFILE_SUCCESS', "Your profile has been successfully removed"); /* r170 */
define('_USER_DELETE_PROFILE_NOTICE', "You can permanently remove your account by clicking the below button."); /* r170 */
define('_USER_DELETE_PROFILE_CONFIRM', "Are you sure you want to permanently REMOVE your profile from %s?"); /* r170, sprintf */
define('_WELCOME_DESC', "Welcome to the user section of our site"); /* r1 */
define('_USER_PASSWORD_INFO', "If you want to change the current password, then fill the below text fields with the same password.\nPlease try to fill the password quality bar for better password security."); /* r424 */
define('_USER_PROFILE', "User profile of %s"); /* r635, sprintf */
define('_USER_PRIVATE_PROFILE', "The following information fields are not publicly shown on this website."); /* r635 */
define('_USER_LAST_VISIT', "Last visit"); /* r950 */
?>