<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_WEBLINKS_TITLE', "Weblinks"); /* r1 */
define('_WEBLINKS_DESC', "Choose one of our weblink topics and visit the relative URLs."); /* r1 */
define('_HEADER_TITLE_WEBLINKS', "Weblink"); /* r1 */
define('_WEBLINKS_SECTION', "Section:"); /* r1 */
define('_SUBMIT_LINK', "Submit a weblink"); /* r1 */
define('_WEBLINKS_EXIST', "There is a weblink already with that name, please try again."); /* r1 */
define('_WEBLINKS_NEED_TITLE', "Your weblink must have a title."); /* r1 */
?>