<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_WEBLINKS_ADDED_SUBJECT', "New weblink added to %s"); /* r1, sprintf, raw */
define('_WEBLINKS_ADDED_MAIL', "A new weblink has been added to %s by user %s (user ID #%d), details follow.\n\nTitle: %s\nURL: %s\nDescription: %s"); /* r1, sprintf, raw */
?>