<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_LOCALE', "en\nen_GB\nEnglish"); /* r1, special */
define('_LOCALE_DEFAULT_TIMEZONE', "Europe/London"); /* r1, special */
define('_NAV_NEXT', "Next"); /* r1 */
define('_NAV_PREV', "Prev"); /* r1 */
define('_NAV_FIRST', "First"); /* r1 */
define('_NAV_LAST', "Last"); /* r1 */
define('_HITS', "Hits"); /* r1 */
define('_DATE', "Date"); /* r1 */
define('_LIKE', "LIKE"); /* r1 */
define('_URL', "URL"); /* r1 */
define('_UPDATE', "Update"); /* r1 */
define('_LANGUAGE_NAME', "English"); /* r1 */
define('_DO_LOGIN', "You need to"); /* r1 */
define('_VALID_AZ09', "Please enter a valid %s with characters 0-9,a-z,A-Z. Maximum length is %d"); /* r1, sprintf */
define('_YES', "Yes"); /* r1 */
define('_NO', "No"); /* r1 */
define('_BUTTON_LOGIN', "Login"); /* r1 */
define('_LOGOUT', "Logout"); /* r1 */
define('_SHOW', "Show"); /* r1 */
define('_HIDE', "Hide"); /* r1 */
define('_SEARCH', "Search"); /* r1 */
define('_SELECTIMAGE', "Select image"); /* r1 */
define('_IMAGEPOS', "Image position"); /* r1 */
define('_DESC', "Description"); /* r1 */
define('_RECORDS', "Records"); /* r1 */
define('_E_SUBJECT', "Subject"); /* r1 */
define('_AUTHOR', "Author"); /* r1 */
define('_NAME', "Display name"); /* r573 */
define('_USER_NAME', "Username"); /* r1 */
define('_PASSWORD', "Password"); /* r1 */
define('_YOUR_NAME', " Enter your name:"); /* r1 */
define('_EMAIL_PROMPT', " Enter your email address:"); /* r1 */
define('_SIZE', "Size"); /* r1 */
define('_CAT', "Category"); /* r1 */
define('_SELECTCAT', "Select category"); /* r1 */
define('_TITLE', "Title"); /* r1 */
define('_SAVE', "Save"); /* r1 */
define('_CANCEL', "Cancel"); /* r1 */
define('_DELETE', "Delete"); /* r1 */
define('_PRINT', "Print"); /* r1 */
define('_PDF', "PDF"); /* r1 */
define('_EMAIL', "Email"); /* r1 */
define('_PARENT', "Parent"); /* r1 */
define('_ORDERING', "Ordering"); /* r1 */
define('_ACCESS', "Access group"); /* r1 */
define('_SELECT', "--- Select"); /* r1 */
define('_NEXT', "Next"); /* r1 */
define('_NEXT_ARROW', " &gt;&gt;"); /* r1 */
define('_PREV', "Prev"); /* r1 */
define('_PREV_ARROW', "&lt;&lt; "); /* r1 */
define('_SORT_NONE', "No sorting"); /* r1 */
define('_SORT_ASC', "Sort ascending"); /* r1 */
define('_SORT_DESC', "Sort descending"); /* r1 */
define('_NEW', "New"); /* r1 */
define('_NONE', "None"); /* r1 */
define('_LEFT', "Left"); /* r1 */
define('_RIGHT', "Right"); /* r1 */
define('_CENTER', "Center"); /* r1 */
define('_PUBLISHED', "Published"); /* r1 */
define('_UNPUBLISHED', "Unpublished"); /* r1 */
define('_FOLDER', "Folder"); /* r1 */
define('_SUBFOLDER', "Sub-folder"); /* r1 */
define('_OPTIONAL', "Optional"); /* r1 */
define('_REQUIRED', "Required"); /* r1 */
define('_CONTINUE', "Continue"); /* r1 */
define('_EDITGROUP', "Edit group"); /* r1 */
define('_USERS_GRP_0', "Public"); /* r1 */
define('_USERS_GRP_1', "Registered"); /* r1 */
define('_USERS_GRP_2', "Editor"); /* r1 */
define('_USERS_GRP_3', "Publisher"); /* r1 */
define('_USERS_GRP_4', "Manager"); /* r1 */
define('_USERS_GRP_5', "Administrator"); /* r1 */
define('_USERS_GRP_9', "Nobody"); /* r1 */
define('_LANGUAGE', "Language"); /* r1 */
define('_SELECTLANG', "Select language"); /* r1 */
define('_ANONYMOUS', "Anonymous"); /* r1 */
define('_EXISTS', "Exists"); /* r1 */
define('_UPLOAD_TOO_BIG', "The file size of the uploaded file exceeds the maximum allowed of %s"); /* r1, sprintf */
define('_UPLOAD_DISALLOWED_EXT', "Allowed file extensions are %s"); /* r1, sprintf */
define('_UPLOAD_INVALID', "Malformed upload file"); /* r1 */
define('_UPLOAD_TOO_BIG_PHP', "Upload file size is %s, the maximum allowed by PHP is %s"); /* r1, sprintf */
define('_UPLOAD_BROKEN', "The file you are trying upload was only partially uploaded"); /* r1, sprintf */
define('_UPLOAD_UNKOWN_ERROR', "Unknown error during file upload, error code: %d"); /* r1, sprintf */
define('_UPLOAD_EXISTS', "A file with that name already exists"); /* r1 */
define('_UPLOAD_CANNOT_READ', "Cannot read uploaded file content"); /* r1 */
define('_UNAUTHORIZED_ACCESS', "Unauthorized access"); /* r1 */
define('_UNAUTHORIZED_ACCESS_DESC', "You are not authorized to access to this resource."); /* r1 */
define('_EDITOR_SHOW_SIMPLE', "Show simple editor"); /* r1 */
define('_EDITOR_SHOW_ADVANCED', "Show advanced editor"); /* r1 */
define('_RELOAD_CAPTCHA', "Reload"); /* r1 */
define('_NO_ANSWER_MSG', "--\n  Please do not answer to this message as it is automatically generated for information purposes only"); /* r1 */
define('_CONTENTIMG_BUTTON', "Image manager"); /* r1 */
define('_CONTENTIMG_DISABLED', "Image manager is currently disabled"); /* r1 */
define('_CONTENTIMG_TITLE', "Lanius CMS content image manager"); /* r1 */
define('_SECTION', "Section"); /* r1 */
define('_USER_TIMEZONE', "User timezone"); /* r1 */
define('_SUBMIT', "Submit"); /* r1 */
define('_SE_NOT_FOUND', "Page not found"); /* r1 */
define('_SE_ACCESS_DENIED', "Access denied"); /* r1 */
define('_SE_OFFLINE', "Offline"); /* r1 */
define('_SE_BAD_REQUEST', "Request is not well formed"); /* r1 */
define('_NA', "N.A."); /* r1 */
define('_ADD', "Add"); /* r1 */
define('_FILE_UPLOAD_LOG', "%s has uploaded file %s"); /* r1, raw, sprintf */
define('_TARGET_INSTANCE', "Default selected instance"); /* r1 */
define('_THUMBNAILER_ASPNET_FAIL', "Could not retrieve thumbnail through ASP.NET"); /* r1, raw */
define('_THUMBNAILER_ASPNET_NA', "GD library/ASP.NET not available, could not generate thumbnail for %s"); /* r1, raw, sprintf */
define('_MODULES_POS_LEFT', "Left"); /* r1 */
define('_MODULES_POS_RIGHT', "Right"); /* r1 */
define('_MODULES_POS_TOP', "Top"); /* r1 */
define('_MODULES_POS_BOTTOM', "Bottom"); /* r1 */
define('_MODULES_POS_INSET', "Inset"); /* r1 */
define('_MODULES_POS_BANNER', "Banner"); /* r1 */
define('_MODULES_POS_DEBUG', "Debug"); /* r1 */
define('_MODULES_POS_HEAD', "Head tag"); /* r1 */
define('_MODULES_POS_USER', "User"); /* r1 */
define('_LOGIN_VIA_HTTP', "Login via HTTP authentication..."); /* r1 */
define('_LOGIN_CLEAR_PW_REQUIRED', "This service requires specific password security options."); /* r1 */
define('_LOGIN_CHANGE_PW', "Please change your password in order to enable it."); /* r1 */
define('_LOGIN_CLEAR_PW_DISABLED', "The website administrator has disallowed them."); /* r1 */
define('_LDAP_CONNECT_FAILED', "ldap_connect() failed"); /* r1 */
define('_WRAPPER_NOT_FOUND_P', "Wrapped path/URL is not readable: %s"); /* r1, sprintf */
define('_WRAPPER_NOT_FOUND', "Wrapped path/URL is not readable"); /* r1 */
define('_USER_VALID_UNIX', "Please specify a valid lowercase UNIX user name"); /* r170, raw */
define('_USER_UNAME_INUSE', "This username is already in use."); /* r1 */
define('_USER_EMAIL_INUSE', "This email is already registered. If you forgot the password click on \"Lost your Password\" and the new password will be sent to you."); /* r1, raw */
define('_EMAIL_NOT_VALID', "Invalid email address specified."); /* r170, raw */
define('_CMS_PASSWORD_QUALITY', "Password quality"); /* r1027 */
define('_DATE_FORMAT_LC', "%A, %d %B %Y"); /* r1, date */
define('_FORM_NC', "Please correctly fill all necessary fields."); /* r1 */
define('_SUBJECT_PROMPT', "Enter your message subject:"); /* r1 */
define('_LOGIN_INCOMPLETE', "Please complete the username and password fields."); /* r1 */
define('_LOGIN_BLOCKED', "Your login has been blocked. Please contact the administrator for more information."); /* r1 */
define('_LOGIN_INCORRECT', "Incorrect username/password."); /* r1 */
define('_BUTTON_RESULTS', "Results"); /* r1 */
define('_LOST_PASSWORD', "I forgot the password"); /* r1 */
define('_NO_ACCOUNT', "No account yet?"); /* r1 */
define('_CREATE_ACCOUNT', "Create one"); /* r1 */
define('_VOTE_POOR', "Poor"); /* r1 */
define('_VOTE_BEST', "Best"); /* r1 */
define('_USER_RATING', "User rating"); /* r1 */
define('_RATE_BUTTON', "Rate"); /* r1 */
define('_REMEMBER_ME', "Remember me"); /* r1 */
define('_UNAME_INUSE', "This username already in use."); /* r1 */
define('_PN_PAGE', "Page %d of %d"); /* r1, sprintf */
define('_PN_START', "Start"); /* r1 */
define('_PN_PREVIOUS', "Prev"); /* r1 */
define('_PN_NEXT', "Next"); /* r1 */
define('_PN_END', "End"); /* r1 */
define('_PN_DISPLAY_NR', "Display #"); /* r1 */
define('_PN_RESULTS', "Results"); /* r1 */
define('_SEND', "Send"); /* r1 */
define('_PROMPT_CLOSE', "Close Window"); /* r1 */
define('_WRITTEN_BY', "Written by"); /* r1 */
define('_LAST_UPDATED', "Last updated"); /* r1 */
define('_LEGEND', "Legend"); /* r1 */
define('_E_EDIT', "Edit"); /* r1 */
define('_E_WARNCAT', "Please select a category"); /* r1 */
define('_E_TITLE', "Title:"); /* r1 */
define('_E_SAVE', "Save"); /* r1 */
define('_E_RESET', "Reset"); /* r1 */
define('_E_ITEM_SAVED', "Item succesfully saved. Your submission will be reviewed before being published."); /* r1 */
define('_ITEM_SAVED_PUBLISHED', "Item succesfully saved and published."); /* r1 */
define('_ITEM_PREVIOUS', "&lt; Prev"); /* r1 */
define('_ITEM_NEXT', "Next &gt;"); /* r1 */
define('_ALREADY_VOTE', "You have already voted for this poll today!"); /* r1 */
define('_THANKS', "Thanks for your vote!"); /* r1 */
define('_CHECKED_IN', "Checked in "); /* r1 */
define('_CHECKED_IN_ITEMS', " items"); /* r1 */
define('_CAPTCHA_VALID_CODE', "Validation Code:"); /* r1 */
define('_CAPTCHA_INCORRECT_CODE', "Incorrect validation code!"); /* r1 */
define('_RETURN_TO_CAT', "Return to submission category"); /* r1 */
define('_SUBMIT_SUCCESS', "Submission accomplished!"); /* r1 */
define('_PATHWAY_PERMA_LINK', "Permanent link to this page"); /* r1 */
define('_PATHWAY_HOME_LINK', "Home page"); /* r1 */
define('_INSTANCE_ERROR', "Menu instance of component does not exist or is not accessible"); /* r1 */
define('_LDAP_ENTRY_ERROR', "Cannot find user entry in LDAP tree"); /* r566 */
?>