<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_TEMPLATES_EDIT_CSS_UI', "Edit template UI CSS"); /* r688 */
?>