<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SYSTEM_NEW_TAR', "New backup"); /* r1 */
define('_SYSTEM_TARBAK_COMPLETE', "Operation completed, the full backup of your website is available here"); /* r1 */
define('_BACKUP_TARBAK_NW_BACKUP', "You backups folder %s is not writable, the tarball backup will be served as download once created"); /* r1, sprintf */
define('_BACKUP_CREATE_N_DOWNLOAD', "Create &amp; download"); /* r1 */
define('_BACKUP_COMPLETE', "complete"); /* r1 */
define('_BACKUP_NOTICE', "delete unused backup files after download"); /* r1 */
define('_BACKUP_RESTORE', "Restore"); /* r170 */
define('_BACKUP_UPDATE_IN_PROGRESS', "Archive update in progress"); /* r1 */
define('_BACKUP_TARBAK_OPTIONS', "Select options for Tarball archive creation"); /* r1 */
define('_BACKUP_TARBAK_INTRO', "Tarball archive will be saved into %s folder"); /* r1, sprintf */
define('_BACKUP_TARBAK_START', "Select the below option to start downloading the file right after the end of the process (can timeout, only for small sites)"); /* r1 */
define('_BACKUP_TARBAK_AUTO_DL', "Download when finished"); /* r1 */
define('_BACKUP_TARBAK_GZ', "If compression is disabled files will be stored in their full size"); /* r1 */
define('_BACKUP_TARBAK_COMPRESS', "Enable compression"); /* r1 */
define('_BACKUP_TARBAK_FF', "No existing database backups will be added to the archive, please check this option to add the current database snapshot"); /* r672 */
define('_BACKUP_TARBAK_SQL', "Attach SQL database snapshot"); /* r1 */
define('_BACKUP_TARBAK_DBF_DESC', "This option makes sense only if you are using a flatfile database. You can include the database directory files if you are moving the website and if you are NOT going to use the database with a different version of Lanius CMS; otherwise you should use an SQL database snapshot, which is portable to new versions of Lanius CMS"); /* r688 */
define('_BACKUP_TARBAK_DBF', "Include database directory"); /* r688 */
define('_BACKUP_TARBAK_RESTART', "Session data lost! Please restart the process"); /* r911 */
define('_BACKUP_TARBAK_ARCHIVING', "Archiving"); /* r1 */
define('_BACKUP_NOTE', "Note"); /* r1 */
define('_BACKUP_USER_DATA_ONLY', "Backup user data only and skip Lanius CMS source files"); /* r1 */
define('_BACKUP_USER_DATA_ONLY_DESC', "Only user-created data under folders %sdownloads, media/ (except media/common), templates/ and %sconfig.php file will be backed up; you will need to re-install Lanius CMS, restore the current SQL database backup and then overwrite manually extracting the archive content"); /* r1, sprintf */
?>