<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_BANNERS_HEAD', "Banner Manager"); /* r1 */
define('_BANNERS_NAME', "Banner Name"); /* r1 */
define('_BANNERS_IMPRESS', "Impressions"); /* r1 */
define('_BANNERS_EDIT', "Edit Banner"); /* r1 */
define('_BANNERS_NEW', "New Banner"); /* r1 */
define('_BANNERS_IMAGE', "Banner Image"); /* r1 */
define('_BANNERS_CLICK_URL', "Banner click URL"); /* r1 */
define('_BANNERS_CODE', "Banner javascript code"); /* r1 */
define('_BANNERS_BLANK_TARGET', "Open in new window"); /* r1 */
?>