<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_COMMENT_HEADER', "Manage Comment Entries"); /* r1 */
define('_COMMENT_HEADER_EDIT', "Edit Comment Entries"); /* r1 */
define('_COMMENT_TITLE', "Article Title"); /* r1 */
define('_COMMENT_POSTED_BY', "Posted by"); /* r1 */
define('_COMMENT_DATE_POSTED', "Date posted "); /* r1 */
define('_COMMENT_CONTENT', "Content"); /* r1 */
define('_COMMENT_CONTENT_DESC', "Edit Comments Entry"); /* r1 */
define('_COMMENT_NAME', "Name"); /* r1 */
define('_COMMENT_COMMENT', "Comment"); /* r1 */
define('_COMMENT_COMMENTS', "Comment(s)"); /* r1 */
?>