<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_CONFIG_HEAD', "Global Configuration"); /* r1 */
define('_CONFIG_SITE', "Website"); /* r1 */
define('_CONFIG_SITE_EXP', "Website settings"); /* r1 */
define('_CONFIG_SITE_TITLE', "Website title"); /* r1 */
define('_CONFIG_SITE_URL', "Website URL"); /* r1 */
define('_CONFIG_SITE_ONLINE', "Website online"); /* r1 */
define('_CONFIG_SITE_STATS', "Always update simple statistics (requires more resources)"); /* r1 */
define('_CONFIG_SITE_OFFMESSAGE', "Offline message"); /* r1 */
define('_CONFIG_LOCALE', "Locale"); /* r1 */
define('_CONFIG_MAILING_SYSTEM', "Mailing system test"); /* r942 */
define('_CONFIG_MAILING_SYSTEM_RESULTS', "Test results"); /* r942 */
define('_CONFIG_MAILING_SYSTEM_SUCCESS', "Email sent successfully"); /* r942 */
define('_CONFIG_MAILING_SYSTEM_FAILURE', "Could not send test email"); /* r942 */
define('_CONFIG_LOCALE_EXP', "Locale settings"); /* r1 */
define('_CONFIG_LOCALE_OFFSET', "Server time offset to GMT"); /* r1 */
define('_CONFIG_LOCALE_SHOWCOUNT', "Number of row items shown in admin backend tables"); /* r1 */
define('_CONFIG_CONTENT', "Content"); /* r1 */
define('_CONFIG_CONTENT_EXP', "Content settings"); /* r1 */
define('_CONFIG_CONTENT_AUTHOR', "Hide author name"); /* r1 */
define('_CONFIG_CONTENT_CREATE', "Hide creation date"); /* r1 */
define('_CONFIG_CONTENT_MODIFIED', "Hide modification date"); /* r1 */
define('_CONFIG_CONTENT_PRINT', "Hide print icon"); /* r1 */
define('_CONFIG_CONTENT_EMAIL', "Hide email icon"); /* r1 */
define('_CONFIG_NOT_WRITABLE', "config.php is not writable"); /* r1 */
define('_CONFIG_MAX_FILE_UPLOAD', "Max client side upload file size (0 = inherit from PHP configuration, default is PHP's value)"); /* r1 */
define('_CONFIG_DB', "Database"); /* r1 */
define('_CONFIG_DB_EXP', "Database Settings"); /* r1 */
define('_CONFIG_DB_DESC', "Warning: do not edit these settings if you are not sure that the new database settings will work"); /* r1 */
define('_CONFIG_GENERAL', "General"); /* r1 */
define('_CONFIG_GENERAL_EXP', "General Lanius CMS and server settings"); /* r1 */
define('_CONFIG_FORCE_TEXT_EMAIL', "Convert all HTML emails sent from the server to text format"); /* r1 */
define('_CONFIG_SERVER_GZIP', "Enable site compression (http gzip)"); /* r1 */
define('_CONFIG_SERVER_SEO', "Maximum number of characters for search engine friendly URLs"); /* r1 */
define('_CONFIG_SERVER_OB', "Always force output buffering"); /* r1 */
define('_CONFIG_SERVER_ERROR', "Error reporting"); /* r1 */
define('_CONFIG_SIMPLE', "Simple"); /* r1 */
define('_CONFIG_DEBUG', "Debug"); /* r1 */
define('_CONFIG_AUTO_SUBMIT', "Auto-submit"); /* r1 */
define('_CONFIG_LOCALE_FALLBACK_LANGUAGE', "Fallback language"); /* r170 */
define('_CONFIG_LOCALE_FALLBACK_LANGUAGE_DESC', "This is NOT the CMS language, but the language that will be used when the user-defined language is no more available and/or when the browser supplied language is not available."); /* r170 */
define('_CONFIG_LOCALE_TS_DETECT', "Detect from external timeserver (GMT)"); /* r1 */
define('_CONFIG_SEARCH_DESC', "General website description"); /* r1 */
define('_CONFIG_SEARCH_INTRO', "Keywords and description specified here will be used on each page served by Lanius CMS, followed by page-specific keywords and description. Feel free not to specify them considering that the specific data will always be automatically generated."); /* r1 */
define('_CONFIG_SEARCH_KEYWORDS', "General keywords"); /* r1 */
define('_CONFIG_EMAIL_EXP', "Settings inherent to emails sent through Lanius CMS"); /* r1 */
define('_CONFIG_EMAIL_SPLIT', "Split multiple recipient emails (Bcc) into single recipient emails (requires more resources)"); /* r1 */
define('_CONFIG_EMAIL_HASHCASH', "Generate hashcash header for"); /* r1 */
define('_CONFIG_EMAIL_HASHCASH_SINGLE', "Single recipient emails"); /* r1 */
define('_CONFIG_EMAIL_HASHCASH_MULTI', "Single and multiple recipient emails"); /* r1 */
define('_CONFIG_SERVER_EVENT', "Recipients for site-wide notification emails"); /* r1 */
define('_CONFIG_TEMP_PATH', "Temporary files full path"); /* r387 */
define('_CONFIG_EMAIL_NOTIFY_ADMINS_ONLY', "Administrators only"); /* r1 */
define('_CONFIG_EMAIL_NOTIFY_MANAGERS_ONLY', "Managers only"); /* r1 */
define('_CONFIG_EMAIL_NOTIFY_ADMINS_MANAGERS', "Administrators and managers"); /* r1 */
define('_CONFIG_EMAIL_TEXT', "Send also text version along with HTML messages"); /* r1 */
define('_CONFIG_SERVER_DOCUMENTATION', "Custom documentation server"); /* r1 */
define('_CONFIG_WRITE_MODE', "Assert mode for new/modified files/directories via chmod (usually 0777 or 0755 or 0666, leave empty to disable)"); /* r170 */
define('_CONFIG_SET_OWNER', "Assert specific ownership via chown (valid UID, empty to disable) for new/modified files/directories \n(%s)"); /* r170, sprintf */
define('_CONFIG_SET_GROUP', "Assert specific group permissions via chgrp (valid GID, empty to disable) for new/modified files/directories \n(%s)"); /* r170, sprintf */
define('_CONFIG_CHECK_GROUP', "check the correct group on your local/remote filesystem"); /* r170 */
define('_CONFIG_DEFAULT_GROUP', "check the correct group on your local/remote filesystem, maybe %s"); /* r170, sprintf */
define('_CONFIG_DEFAULT_OWNER', "check the correct owner on your local/remote filesystem, maybe %s"); /* r170, sprintf */
define('_CONFIG_CHECK_OWNER', "check the correct owner on your local/remote filesystem"); /* r170 */
define('_CONFIG_HTTP_AUTH', "HTTP Authentication support"); /* r1 */
define('_CONFIG_HTTP_AUTH_NONE', "None"); /* r1 */
define('_CONFIG_HTTP_AUTH_BASIC', "Basic Authentication"); /* r1 */
define('_CONFIG_HTTP_AUTH_DIGEST', "Digest Authentication"); /* r1 */
define('_CONFIG_CLEAR_PW', "Enable clear passwords (for authentication integrations)"); /* r1 */
define('_CONFIG_TEST_EMAIL', "Send test email"); /* r1 */
define('_CONFIG_EMAIL_FROM', "Reliable email address for returned emails and direct replies"); /* r1033 */
define('_CONFIG_EMAIL_FROM_NAME', "Reliable name associated to above email address"); /* r1033 */
define('_CONFIG_PAGECACHE_ENABLE_CACHE', "Enable cache"); /* r1 */
define('_CONFIG_PAGECACHE_CACHE_ENABLE_DEBUG', "Enable cache debugging"); /* r1 */
define('_CONFIG_SQLDEBUG_ENABLE', "Enable SQL queries debugging (needs mod_debug active to see results)"); /* r1001 */
define('_CONFIG_RESOURCE_DENY', "Show 404 errors in place of unauthorized access attempts"); /* r1 */
define('_CONFIG_BACKEND', "Backend"); /* r1 */
define('_CONFIG_BACKEND_EXP', "General options relative to the administrative backend"); /* r1 */
define('_CONFIG_VIEW_FILTER', "Remember filter settings for all views"); /* r1 */
?>