<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_CONTENT_SECTION_HEAD', "Manage Sections"); /* r1 */
define('_CONTENT_SECTION_NEW_HEAD', "New Section"); /* r1 */
define('_CONTENT_SECTION_EDIT_HEAD', "Edit Section"); /* r1 */
define('_CONTENT_ITEM_HEAD', "Manage Content"); /* r1 */
define('_CONTENT_ITEM_NEW_HEAD', "New Content"); /* r1 */
define('_CONTENT_ITEM_EDIT_HEAD', "Edit content"); /* r1 */
define('_CONTENT_ITEM_CONTENT', "Content"); /* r1 */
define('_CONTENT_ITEM_CONTENT_TALIAS', "Title Alias"); /* r1 */
define('_CONTENT_ITEM_CONTENT_INTRO', "Introduction Text"); /* r1 */
define('_CONTENT_ITEM_CONTENT_COMPLETE', "Complete Text"); /* r1 */
define('_CONTENT_ITEM_PUBLISH', "Publish"); /* r1 */
define('_CONTENT_ITEM_PUBLISH_EXP', "Publish settings"); /* r1 */
define('_CONTENT_ITEM_PUBLISH_AALIAS', "Author Alias"); /* r1 */
define('_CONTENT_ITEM_HIDE_TITLE', "Hide title"); /* r1 */
define('_CONTENT_ITEM_HIDE_EMAIL', "Hide email to a friend icon"); /* r1 */
define('_CONTENT_ITEM_HIDE_PRINT', "Hide print icon"); /* r1 */
define('_CONTENT_ITEM_HIDE_AUTHOR', "Hide author"); /* r1 */
define('_CONTENT_ITEM_HIDE_CREATED', "Hide created date"); /* r1 */
define('_CONTENT_ITEM_HIDE_MODIFIED', "Hide modified date"); /* r1 */
define('_CONTENT_ITEM_HIDE_PERMALINK', "Hide permalink"); /* r170 */
define('_CONTENT_ITEM_HIDE_PDF', "Hide export to PDF icon"); /* r1 */
define('_CONTENT_ITEM_EXPORT_CACHE', "Enable caching of unmodified exports"); /* r1 */
define('_CONTENT_ITEM_PUBLISH_FRONTPAGE', "Show on frontpage"); /* r1 */
define('_CONTENT_ITEM_META', "Search"); /* r1 */
define('_CONTENT_ITEM_META_EXP', "Search settings"); /* r1 */
define('_CONTENT_EMAIL_CAPTCHA_LEVEL', "Enable CAPTCHA for send to a friend feature for users below this level"); /* r943 */
define('_CONTENT_ITEM_META_KEYWORDS', "Content keywords"); /* r1 */
define('_CONTENT_ITEM_META_DESC', "Content description"); /* r1 */
define('_CONTENT_ARCHIVE_HEAD', "Manage Archive"); /* r1 */
define('_A_CONTENT_AUTO_FILL', "Auto-fill"); /* r1 */
define('_CONTENT_BLOG_SHOW_COUNT', "Number of entries in blog view"); /* r1 */
define('_CONTENT_CATEGORY_SHOW_COUNT', "Number of entries in category view"); /* r1 */
define('_CONTENT_OPTIONS', "Options"); /* r1 */
define('_CONTENT_ARCHIVED_NO_PUB', "Content is archived"); /* r170 */
define('_CONTENT_OPTIONS_DESC', "These content-item relative options only work as negation to category-relative options. Not being hidden does not mean visible!"); /* r483 */
?>