<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DB_COMPAT_FIX', "Applying compatibility fix for"); /* r1 */
define('_DB_SQL_RESULTS', "SQL results"); /* r1 */
define('_DB_OPERATION_STATUS', "Operation status"); /* r1 */
define('_DB_REBASE_PROGRESS', "Re-basing database"); /* r1 */
define('_DB_IMPORT_NOTICE', "Import notice"); /* r1 */
define('_DB_IMPORT_NOTICE_FACTS', "You are importing a database from an unknown format (it will be considered as the old Limbo CMS format), please take care of the below facts inherent to the completed process"); /* r1 */
define('_DB_IMPORT_NOTICE_FACT_1', "not all admin/user components may work depending from their presence in the previous or current installation (they must be present in both in order to work)"); /* r1 */
define('_DB_IMPORT_NOTICE_FACT_2', "all your previous users will be imported, including those with managerial or administrative roles; if no admin user is present in the source SQL, the current admin user will be recreated in the database"); /* r1 */
define('_DB_FINISHED', "100%% complete, %d total errors in %d executed queries"); /* r1, sprintf */
define('_DKDB_FORMAT', "DKDB format"); /* r1 */
define('_RESTORE_CONFIRM', "Are you sure you want to restore the selected SQL file into the current database?"); /* r1 */
define('_DB_REBASE', "Re-base"); /* r1 */
define('_DB_REBASE_CONFIRM', "Re-basing is a complex operation which reads all the table rows, drops the tables, creates the tables (using the latest schemas) and inserts again each row. If you are not sure that the operation will be completed (for example, due to timeout limits) do not continue or else your database will be incomplete after the re-base operation (and part of your data will be lost).\n\nDo you wish to proceed?"); /* r1 */
define('_BACKUP_CONFIRM', "Proceed to backup the current database?"); /* r1 */
define('_DATABASE_RESTORE', "Restore"); /* r1 */
define('_BACKUP_RESTORED', "Backup restored successfully"); /* r1 */
define('_DB_QUERY_FIELD', "Enter SQL Query"); /* r1 */
define('_DB_QUERY_EXC', "Execute Query"); /* r1 */
define('_DB_QUERY_CLEAR', "Clear"); /* r1 */
define('_DB_QUERY_RESULT', "Query Result"); /* r1 */
define('_DB_QUERY_ROWS', "Result rows"); /* r1 */
define('_DB_QUERY_FIELDS', "Fields"); /* r1 */
define('_DB_QUERY_AFF', "Affected Rows"); /* r1 */
define('_DB_IMPORT_ERROR', "Import error"); /* r1 */
define('_DB_IMPORT_ERROR_WEIRD_DKDB', "The database you are trying to import looks like in Lanius CMS (DKDB) format, but its version could not reliably be recognized."); /* r1 */
define('_DB_IMPORT_ERROR_NOT_LM', "The database you are trying to import is not recognized as a Limbo CMS SQL backup neither is in Lanius CMS (DKDB) format."); /* r1 */
define('_DB_IMPORT_ERROR_SVN', "You are trying to import an SQL backup created with an SVN revision, which is not supported."); /* r1 */
define('_DB_IMPORT_NOTICE_SVN', "You are importing an SQL backup created with an SVN revision, which is not supported.\nThe backup will NOT be imported because SVN backups are not supported and would waste developers' time."); /* r1 */
define('_DB_IMPORT_SOURCE_VER', "Lanius CMS database source"); /* r1 */
define('_DB_IMPORT_SOURCE', "The source database was created with Lanius CMS v%s"); /* r1, sprintf */
define('_BACKUP_ASK_COMPRESS', "Do you want to compress the backup file?"); /* r1, raw */
define('_DB_NO_QUERIES', "No queries executed"); /* r1 */
define('_TB_CREATE_COMPRESSED', "Create (compressed)"); /* r491 */
?>