<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DM_MANAGE', "Manage Downloads"); /* r1 */
define('_DM_MANAGE_CAT', "Manage Download Categories"); /* r1 */
define('_DM_MANAGE_NEW_HEAD', "New Download"); /* r1 */
define('_DM_MANAGE_EDIT_HEAD', "Edit Download"); /* r1 */
define('_DM_IMAGE_URL', "Image URL"); /* r1 */
define('_DM_FILE_SIZE', "File size"); /* r1 */
define('_DOWNLOADS_P_DESC', "Description in download categories index"); /* r1 */
define('_DOWNLOADS_PROTECTED', "Serve file via PHP and not through the webserver\n(may break with huge files &gt; 30MB depending on your PHP memory limits)"); /* r1 */
define('_DOWNLOADS_ANTILEECH', "When serving files via PHP, disallow leechers (and also download accelerators)"); /* r1 */
define('_DOWNLOADS_DELETE_CATEGORY', "Deleting a category will also delete ALL DOWNLOADS in such category. Do you wish to continue?"); /* r492, raw */
?>