<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DRABOTS_INSTALL_HEAD', "Install / Uninstall Drabots"); /* r1 */
define('_DRABOTS_EDIT_HEAD', "Edit Drabot"); /* r1 */
define('_DRABOTS_EDIT_ACTIVE', "Active in following Sections"); /* r1 */
define('_DRABOTS_PARAMS', "Drabot Parameters"); /* r1 */
?>