<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_EVENT_MANAGE', "Manage Events"); /* r1 */
define('_EVENT_TITLE', "Event"); /* r1 */
define('_EVENT_EDIT_HEAD', "Edit Event"); /* r1 */
define('_EVENT_NEW_HEAD', "New Event"); /* r1 */
define('_EVENT_SDATE', "Start Date"); /* r1 */
define('_EVENT_EDATE', "End Date"); /* r1 */
define('_EVENT_INVALID_DATE', "End date should be greater than start date"); /* r1 */
define('_EVENT_INVALID_SDATE', "Invalid start date"); /* r557 */
define('_EVENT_INVALID_EDATE', "Invalid end date"); /* r557 */
define('_EVENT_DEFAULT_SORTING', "Default sorting"); /* r965 */
?>