<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FAQ_QUESTIONS_MANAGE', "Manage questions and answers"); /* r1 */
define('_FAQ_A_QUESTION', "Question posed by user"); /* r1 */
define('_FAQ_A_ANSWER', "Answer given"); /* r1 */
define('_FAQ_EDIT_HEAD', "Edit Question"); /* r1 */
define('_FAQ_NEW_HEAD', "New Question"); /* r1 */
?>