<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FM_HEADER', "File Manager"); /* r1 */
define('_FM_PERMISSION', "Permissions"); /* r1 */
define('_FM_NEW_FILE', "New File"); /* r1 */
define('_FM_CREATE_DIR', "New Directory"); /* r1 */
define('_FM_RENAME', "Rename"); /* r591 */
define('_FM_RENAME_DESC', "Rename (or move) file to specified new name or path."); /* r591 */
define('_FM_RENAME_NEW', "New name/path"); /* r591 */
define('_FM_NEW_FILE_DESC', "Create a file, when done press save to make changes."); /* r1 */
define('_FM_WRITABLE', "Writable"); /* r1 */
define('_FM_NOT_WRITABLE', "Not Writable"); /* r1 */
define('_FM_EDIT_FILE', "Edit File"); /* r1 */
define('_FM_EDIT_DESC', "Edit a file, when done press save to make changes"); /* r1 */
define('_FM_FILE', "File:"); /* r1 */
define('_FM_DIR', "Directory"); /* r1 */
define('_FM_PATH', "Path:"); /* r1 */
define('_FM_FILE_NAME', "File name "); /* r170 */
define('_FM_DIRECTORY_NAME', "Directory name "); /* r170 */
define('_FM_FILE_CONTENT', "File Content "); /* r1 */
define('_FM_INFO', "You can change the permissions of various files or directories which you have selected"); /* r1 */
define('_FM_CHMOD_CALC', "Mode Calculator"); /* r1 */
define('_FM_NEW_MODE', "New Mode"); /* r1 */
define('_FM_NEW_DIR', "New Directory "); /* r1 */
define('_FM_NEW_DIR_DESC', "Create a Directory, when done press save to make changes."); /* r1 */
define('_FM_WARNING_ENCODING', "WARNING: this file, possibly binary, is not UTF-8 encoded, if you save it it through this web interface will be permanently damaged."); /* r545 */
?>