<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FORUM_MANAGE', "Manage forum categories"); /* r1 */
define('_FORUM_MANAGE_CATEGORIES', "Manage forum section categories"); /* r1 */
define('_FORUM_MANAGE_NEW', "New forum category"); /* r1 */
define('_FORUM_MANAGE_SECTIONS', "Manage forum sections"); /* r1 */
define('_FORUM_MANAGE_SECTION_EDIT', "Edit forum section"); /* r1 */
define('_FORUM_MANAGE_SECTION_NEW', "New forum section"); /* r1 */
define('_FORUM_MODERATORS', "Moderators"); /* r1 */
define('_FORUM_MODERATORS_EXP', "Moderator usernames separated by commas"); /* r1 */
define('_FORUM_LOCKED', "Lock forum"); /* r1 */
define('_FORUM_MANAGE_EDIT', "Edit forum category"); /* r1 */
define('_FORUM_CONFIG', "Forum configuration"); /* r1 */
define('_FORUM_REG_POST', "Anonymous users can post"); /* r1 */
define('_FORUM_FILTER_REP', "Replace bad words with"); /* r1 */
define('_FORUM_RE_PREFIX', "Replies prefix"); /* r1 */
define('_FORUM_FILTER_BAD', "Bad words"); /* r1 */
define('_FORUM_DATE', "Date Format"); /* r1 */
define('_FORUM_SHOW_COUNT', "Number of categories or topics to show per page"); /* r1 */
define('_FORUM_EXPAND_SECTIONS', "Expand section categories inline"); /* r1 */
define('_FORUM_VIEW_USER_POSTS', "User posts listing access group"); /* r1 */
define('_FORUM_NOTIFY_NEW_TOPICS', "Notify new topics to moderators/administrators"); /* r842 */
define('_FORUM_ALLOW_AVATAR_UPLOAD', "Allow upload of user avatars"); /* r1 */
define('_FORUM_RESIZE_UPLOADED_AVATARS', "Resize uploaded avatar if height or width is greater than specified value"); /* r1 */
define('_FORUM_ENABLE_SYNDICATION', "Enable forum syndication feeds"); /* r1 */
define('_FORUM_ALLOW_BB_IMG', "Allow [img] tags in BB code"); /* r1 */
?>
