<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FRONTPAGE_SHOW_ICONS', "Show Toolbox Icons (print, send email to friend)"); /* r1 */
define('_FRONTPAGE_2COL_NEWS', "Show News Items in two Columns"); /* r1 */
define('_FRONTPAGE_HEAD_DESC', "At least one content item must be published and active in frontpage in order for the frontpage component to work"); /* r170 */
?>