<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_TB_WIZARD', "Wizard"); /* r1 */
define('_GALLERY_WIZARD', "Gallery Wizard"); /* r1 */
define('_GALLERY_HELP1', "1.    Enter the new category name"); /* r1 */
define('_GALLERY_HELP2', "2. OR Select an existing category to add images to"); /* r1 */
define('_GALLERY_HELP3', "3. OR Select a directory with no category associated"); /* r1 */
define('_GALLERY_NEW_PHOTO', "New image"); /* r1 */
define('_GALLERY_EDIT_PHOTO', "Edit image"); /* r1 */
define('_GALLERY_MANAGE', "Manage gallery items"); /* r1 */
define('_GALLERY_RESIZE', "Proportionally resize to specified maximum width (0 to disable)"); /* r1 */
define('_GALLERY_CATNAME', "New gallery category name"); /* r1 */
define('_GALLERY_SELECT_FOLDER', "Select directory"); /* r1 */
define('_GALLERY_UNFOLDED', "Directories without associated category"); /* r1 */
define('_GALLERY_FIRST', "First image of gallery becomes category image"); /* r1 */
define('_GALLERY_NO_IMAGE', "Select a valid image!"); /* r1 */
define('_GALLERY_THUMBS', "Regenerate thumbnails"); /* r1 */
define('_GALLERY_NO_CATEGORIES', "No categories found"); /* r1 */
define('_GALLERY_CATEGORY_ROWS', "Number of category rows per page"); /* r1 */
define('_GALLERY_PHOTO_ROWS', "Number of image rows per page"); /* r1 */
define('_GALLERY_PHOTO_PER_ROW', "Number of images shown per row"); /* r1 */
define('_GALLERY_SHOW_MODE', "Show single images in"); /* r1 */
define('_GALLERY_SHOW_INSET', "Inset"); /* r1 */
define('_GALLERY_SHOW_WINDOW', "New window"); /* r1 */
define('_GALLERY_SHOW_POPUP', "Popup"); /* r1 */
define('_GALLERY_SHOW_THICKBOX', "Thickbox"); /* r1 */
define('_GALLERY_MAKE_THUMBNAIL', "Re-generate thumbnail on save"); /* r1 */
define('_GALLERY_DESC', "Description in gallery categories index"); /* r1 */
define('_GALLERY_AUTO_RESIZE', "Proportionally resize if width or height is above the specified value (in pixels); specify 0 to disable"); /* r1 */
define('_GALLERY_AUTO_CATEGORY_THUMBNAIL', "If you select no thumbnail the first image of the gallery will automatically be used"); /* r1 */
define('_GALLERY_THUMBNAIL_NOT_AVAILABLE', "Thumbnail not available"); /* r1 */
define('_GALLERY_PATH', "Gallery relative path"); /* r1 */
define('_GALLERY_THUMBS_PATH', "Thumbnails relative path (images must have same filename)"); /* r1 */
define('_GALLERY_MOVE_FAILURE', "New gallery category paths saved, but the following directories could not be moved"); /* r1 */
define('_GALLERY_INVALID_PATH', "Paths can contain only A-Z letters, 0-9 numbers, '.' dot, '-' hyphen and '_' underscore"); /* r1 */
define('_GALLERY_AUTO_CATEGORY_PATHS', "If the below-specified paths do not exist, they will be created; if you leave in the default values paths based on the category name will be computed"); /* r1 */
define('_GALLERY_DIRECTORY_ERROR', "Cannot create the gallery category directories"); /* r1, raw */
define('_GALLERY_SEND_THUMBNAIL', "Send thumbnail of submitted images to administrator(s)"); /* r1 */
?>