<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SITEMAP_HEAD', "Google Sitemap"); /* r170 */
define('_SITEMAP_DESC', "Click on Create to create the Google Sitemap"); /* r170 */
define('_SITEMAP_CREATED', "Google Sitemap created"); /* r1 */
define('_SITEMAP_COUNT_INDEXED', "content items indexed"); /* r1 */
define('_SITEMAP_FROM', "Your Google Sitemap will be accessible from"); /* r1 */
?>