<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_GUESTBOOK_A_TITLE', "Guestbook"); /* r1 */
define('_GUESTBOOK_EDIT', "Edit Guestbook"); /* r1 */
define('_GUESTBOOK_A_COUNTRY', "Country"); /* r1 */
define('_GUESTBOOK_IP', "IP Address"); /* r1 */
define('_GUESTBOOK_A_REPLY', "Reply"); /* r1 */
define('_GUESTBOOK_FLOOD_TIMEOUT', "Flooding timeout (minutes)"); /* r1 */
define('_GUESTBOOK_EMAIL_SHOW', "Show email to users of group"); /* r1 */
define('_GUESTBOOK_EMAIL_OBFUSCATE', "Obfuscate email"); /* r1 */
define('_GUESTBOOK_CAPTCHA', "Enable CAPTCHA test for user less privileged than"); /* r1 */
define('_GUESTBOOK_A_MESSAGE', "Message"); /* r556 */
?>