<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_LANGUAGE_RESOURCES', "Language Resources"); /* r1 */
define('_LANGUAGE_ALREADY_EXISTS', "Language resources for country code %s already exist! Edit or remove them."); /* r1, sprintf */
define('_LANGUAGE_CC', "Assigned Country Code"); /* r1 */
define('_LANGUAGE_CREATE', "Create Language"); /* r1 */
define('_LANGUAGE_VERSION', "Version"); /* r1 */
define('_LANGUAGE_REPAIR', "Repair"); /* r1 */
define('_LANGUAGE_RESOURCES_ADDED', "resources added"); /* r1 */
define('_LANGUAGE_NEW_FILE ', "added new file"); /* r617 */
define('_LANGUAGE_RESOURCES_REMOVED', "resources removed"); /* r1 */
define('_LANGUAGE_REMOVED', "removed"); /* r1 */
define('_LANGUAGE_ADDED', "added"); /* r1009 */
define('_LANGUAGE_CANNOT_FIND', "Could not find %s language files"); /* r1, sprintf */
define('_LANGUAGE_UP_TO_DATE', "Language files were up to date and did not need repair"); /* r1 */
define('_LANGUAGE_REPAIRED', "Language Files successfully repaired"); /* r1 */
define('_LANGUAGE_INFO_CLONE', "Language %s will be used as base for the new translation"); /* r1, sprintf */
define('_LANGUAGE_INFO_CC', "For more info about country codes, see"); /* r1 */
define('_LANGUAGE_TRANSLATE_INFO', "Do you want to translate Lanius CMS into your language? Click here for more information"); /* r1 */
define('_LANGUAGE_EDIT_STATUS', "Path: %s is %s"); /* r1, sprintf */
define('_LANGUAGE_RES_COUNT', "%s resources on this tab"); /* r1, sprintf */
define('_LANGUAGE_OUTDATED', "outdated"); /* r1 */
define('_SAVE_AND_BACK', "Save & edit again"); /* r1, raw */
define('_LANGUAGE_INVALID_SELECTION', "Please select a valid language"); /* r1 */
define('_LANGUAGE_NORMALIZE', "Normalize"); /* r1 */
define('_LANGUAGE_VERIFY', "Verify"); /* r1 */
define('_LANGUAGE_OUT_OF_DATE', "Out of date"); /* r1 */
define('_LANGUAGE_UPDATED', "Updated"); /* r1 */
define('_LANGUAGE_CANNOT_REMOVE_BASE', "Cannot remove base language"); /* r1039, raw */
define('_LANGUAGE_SPECIAL_NOTICE', "This is a special language resource, \nyou do not have to translate it;\n read the documentation for more information"); /* r1 */
define('_LANGUAGE_NORMALIZE_ALERT', "Language resources normalization will rewrite each language file; you should apply normalization only if there have been manual edits (which are deprecated, by the way) to the language files because it would be a waste of time if you are otherwise using only this language component to perform the translation.\n\nNormalize all language files for selected language?"); /* r1 */
?>