<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_LOGIN_HTTP_AUTH', "Allow login via HTTP Authentication"); /* r1 */
define('_LOGIN_HTTP_AUTH_NONE', "None"); /* r1 */
define('_LOGIN_HTTP_AUTH_BASIC', "Basic Authentication"); /* r1 */
define('_LOGIN_HTTP_AUTH_DIGEST', "Digest Authentication"); /* r1 */
define('_LOGIN_CAPTCHA', "Enable CAPTCHA verification"); /* r1 */
?>