<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MASSMAIL_HEAD', "Mass Mail"); /* r1 */
define('_MASSMAIL_SEND', "Send"); /* r1 */
define('_MASSMAIL_SUBJECT', "Subject of Email"); /* r1 */
define('_MASSMAIL_EMAIL', "Send Email to"); /* r1 */
define('_MASSMAIL_NEWS', "Complete News"); /* r1 */
define('_MASSMAIL_ALL', "All Users and Admins"); /* r1 */
define('_MASSMAIL_SENT', " Emails sent"); /* r1 */
define('_MASSMAIL_HELP', "Use {email}, {name} and {username} to include specific properties of the recipient in your email"); /* r1 */
define('_MASSMAIL_INCLUSIVE', "Consider as minimum level"); /* r1 */
define('_MASSMAIL_TEXT', "Send this email as raw text"); /* r1 */
?>