<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MENU_TYPE_COMPONENT', "Component instance"); /* r1 */
define('_MENU_TYPE_SECTION', "Content section"); /* r1 */
define('_MENU_TYPE_CATEGORY', "Content category"); /* r1 */
define('_MENU_TYPE_BLOG', "Content category (blog style)"); /* r1 */
define('_MENU_TYPE_ITEM', "Content item"); /* r1 */
define('_MENU_TYPE_CLINK', "Clone link"); /* r1 */
define('_MENU_TYPE_SEPARATOR', "Separator"); /* r1 */
define('_MENU_TYPE_LINK', "URL link"); /* r1 */
define('_MENU_TYPE_WRAPPER', "Wrapper"); /* r1 */
define('_MENU_HEAD', "Manage menu categories"); /* r1 */
define('_MENU_MANAGE', "Manage menu items in %s"); /* r1, sprintf */
define('_MENU_CREATE_HEAD', "Create New Menu"); /* r1 */
define('_MENU_NEW_HEAD', "New menu item"); /* r1 */
define('_MENU_EDIT_HEAD', "Edit menu item"); /* r911 */
define('_MENU_NEW_TYPE', "Select menu type"); /* r1 */
define('_MENU_COMPONENT_NEW_HEAD', "New Menu Item :: Component"); /* r1 */
define('_MENU_COMPONENT_EDIT_HEAD', "Edit Menu Item :: Component"); /* r1 */
define('_MENU_CONTENT_ITEM_ERROR', "No Content items have been defined by you which can be linked.\nPlease go to Content -&gt; Content -&gt; Content Items and create new content and come back."); /* r1 */
define('_MENU_TOP', "-- Top level"); /* r170 */
define('_MENU_SPACERTEXT', "Top"); /* r1 */
define('_MENU_CLINK_SELECT', "Please select a link to clone"); /* r1 */
define('_MENU_LINK_ONEW', "New Window"); /* r1 */
define('_MENU_LINK_OCUR', "Parent Window"); /* r1 */
define('_MENU_LINK_OPOPUP', "Popup window"); /* r1 */
define('_MENU_LINK_POPMENU', "Show children only when menu instance is active"); /* r170 */
define('_MENU_PARENT_MENU', "Parent menu"); /* r1 */
define('_MENU_INSTANCE_NOTICE', "NOTE: you are deleting a component instance menu item, be sure that there are no modules or drabots using component '%s' before continuing. If there are, it is suggested to move these menu items to an unpublished menu instead (default is hiddenmenu)"); /* r1, raw, sprintf */
?>