<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MSG_HEAD', "Message Center"); /* r1 */
define('_MSG_STATUS', "Status"); /* r1 */
define('_MSG_STATUS_READ', "Read"); /* r1 */
define('_MSG_STATUS_REPLIED', "Replied"); /* r1 */
define('_MSG_FROM', "From"); /* r1 */
define('_MSG_POSTED', "Posted on"); /* r1 */
define('_MSG_RE', "Re"); /* r1 */
define('_MSG_EDIT_HEAD', "Read / Reply Messages"); /* r1 */
define('_MSG_SUBJECT', "Subject"); /* r1 */
define('_MSG_MESSAGE', "Message body"); /* r684 */
define('_MSG_EDIT_REPLY_BODY', "Reply to Message"); /* r1 */
define('_MSG_VIEW_HEAD', "View Message"); /* r1 */
define('_MSG_EDIT_REPLY_TITLE', "Title of Reply"); /* r1 */
define('_MSG_REPLY', "Reply"); /* r1 */
define('_MSG_REPLY_WROTE', "%s wrote:"); /* r1, sprintf */
define('_MSG_READ', "Read"); /* r1 */
define('_CONTACT_CAPTCHA', "CAPTCHA test before contact form submission"); /* r1 */
define('_CONTACT_ALLOW_ATTACHMENT', "Allow attachments"); /* r1 */
define('_MESSAGE_RECP_LIST', "Show users in recipients list using"); /* r422 */
define('_MESSAGE_RECP_LIST_USERNAME', "Username"); /* r422 */
define('_MESSAGE_RECP_LIST_NAME', "Real name"); /* r422 */
define('_MESSAGE_RECP_LIST_BOTH', "Username and real name"); /* r422 */
define('_MESSAGE_MULTIPLE_RECP', "Allow sending to multiple recipients"); /* r422 */
define('_MESSAGE_DELIVER', "Deliver full message through email"); /* r422 */
define('_MESSAGE_STORE_MODE', "Email storage settings"); /* r422 */
define('_MESSAGE_STORE_NONE', "Do not store email"); /* r422 */
define('_MESSAGE_STORE', "Save email in user's inbox"); /* r422 */
define('_MESSAGE_STORE_SN', "Save email in user's inbox and notify him"); /* r422 */
define('_MESSAGE_MAXIMUM_SIZE', "Maximum message length (in bytes)"); /* r422 */
define('_MESSAGE_RECP_MIN_GID', "Minimum access level of receivers"); /* r422 */
?>