<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MODULES_INSTALL_HEAD', "Install / Uninstall Modules"); /* r1 */
define('_MODULES_POSITION', "Position"); /* r1 */
define('_MODULES_EDIT_HEAD', "Edit Module"); /* r1 */
define('_MODULES_NEW_HEAD', "New Module Instance"); /* r1 */
define('_MODULES_NEW_INSTANCE', "Module Instance of"); /* r1 */
define('_MODULES_EDIT_STITLE', "Show Title"); /* r1 */
define('_MODULES_PARAMS', "Module Parameters"); /* r1 */
define('_MODULES_SHOW_ON', "Show on"); /* r1 */
define('_MODULE_ID', "Module ID"); /* r1 */
?>