<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_POLLS_MANAGE', "Manage Polls"); /* r1 */
define('_POLLS_A_OPTIONS', "# of Options"); /* r1 */
define('_POLLS_A_ID', "Poll ID"); /* r1 */
define('_POLLS_NEW_HEAD', "New Poll"); /* r1 */
define('_POLLS_EDIT_HEAD', "Edit Poll"); /* r1 */
define('_POLLS_A_QUESTION', "Poll Question"); /* r1 */
define('_POLLS_VOPTIONS', "Various Poll Options"); /* r1 */
define('_POLLS_A_OPTION', "Option"); /* r1 */
define('_POLLS_RESET', "Reset"); /* r1 */
define('_POLL_A_ID', "Poll ID (use 0 to show polls selection)"); /* r1 */
define('_POLL_VOTE_DELAY', "Delay between votes"); /* r1 */
?>