<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_REGISTRATION_USERS_PUBLISHED', "New user is automatically active"); /* r170 */
define('_REGISTRATION_NEW_USERS', "Enable new users registration"); /* r170 */
define('_REGISTRATION_CONFIRM_MODE', "Registration confirmation mode"); /* r439 */
define('_REGISTRATION_NEW_PASS', "Lost password mode"); /* r170 */
define('_REGISTRATION_EMAIL_PASSWORD', "Send plain password in activation/registration emails"); /* r1 */
define('_REGISTRATION_CAPTCHA', "CAPTCHA test before registration submission"); /* r1 */
define('_REGISTRATION_A_XUP_SUPPORT', "Enable XUP support"); /* r1 */
define('_REGISTRATION_NOTIFY', "Send notification email on new user registration"); /* r1 */
define('_REGISTRATION_MODE_UPNE', "Users can specify a password which is not received via email"); /* r170 */
define('_REGISTRATION_MODE_UPE', "Users can specify a password and they will receive it via email"); /* r170 */
define('_REGISTRATION_NP_MODE_UP', "The current password is sent to user (requires clear passwords ON)"); /* r170 */
define('_REGISTRATION_MODE_NP', "A new password is created and sent to user"); /* r170 */
define('_REGISTRATION_MODE_AL', "An activation link is sent to users which are then allowed to change their password"); /* r170 */
define('_REGISTRATION_USERS_PUBLISHED_DESC', "When the below setting is set to Yes, new users are automatically active unless you have selected activation link for registration confirmation mode"); /* r170 */
?>