<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SERVICE_XML_RPC', "Enable XML RPC services"); /* r1 */
define('_SERVICE_CAPTCHA', "Enable CAPTCHA service"); /* r1 */
?>