<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_ADMIN_START_NEWS', "New Items not yet reviewed"); /* r1 */
define('_START_DOWNLOADS', "Downloads"); /* r1 */
define('_START_FAQ', "FAQ"); /* r1 */
define('_START_GALLERY', "Gallery"); /* r1 */
define('_START_HEAD', "Manage your website"); /* r475 */
define('_START_FEED', "Keep yourself updated"); /* r1 */
define('_START_FEED_DESC', "Bookmark this RSS feed and stay tuned about Lanius CMS news."); /* r1 */
define('_START_POST', "Post News or create a Page"); /* r1 */
define('_START_POST_DESC', "Post news or create a new content page; you can also create new sections."); /* r1 */
define('_START_USERS', "Manage your users"); /* r475 */
define('_START_USERS_DESC', "Change the language of your user accounts, add/remove them and associate them to different access groups."); /* r1 */
define('_START_TEMPLATE', "Change frontend template"); /* r475 */
define('_START_TEMPLATE_DESC', "Change your website's look, install new templates or edit the template to fit your needs."); /* r1 */
define('_START_HELP', "Documentation"); /* r1 */
define('_START_HELP_DESC', "Do you need help? Read the official documentation."); /* r1 */
define('_START_ABOUT', "Lanius CMS!"); /* r1 */
define('_START_ABOUT_DESC', "Information about Lanius CMS"); /* r475 */
define('_START_CONFIG', "Edit your Configuration"); /* r1 */
define('_START_CONFIG_DESC', "Change general settings of your website."); /* r1 */
define('_START_BACKUP', "Backup your Database"); /* r1 */
define('_START_BACKUP_DESC', "Create a backup of your website database."); /* r1 */
?>