<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SUBSITES_SUBPATH', "Subpath"); /* r1 */
define('_SUBSITES_STATUS', "Status"); /* r1 */
define('_SUBSITES_EDIT', "Edit subsite"); /* r1 */
define('_SUBSITES_NEW', "New subsite"); /* r1 */
define('_SUBSITES_INVALID_PATH', "Invalid Path"); /* r1 */
define('_SUBSITES_ONLINE', "Online"); /* r1 */
define('_SUBSITES_OFFLINE', "Offline"); /* r1 */
define('_SUBSITES_TABLE_PREFIX', "Subsite table prefix"); /* r1 */
define('_SUBSITES_TITLE', "Subsite title"); /* r1 */
define('_SUBSITES_IS_ONLINE', "Subsite is online"); /* r1 */
define('_SUBSITES_CONFIGURE', "Configure after creation"); /* r1 */
define('_SUBSITES_DIR_EXISTS', "The specified subsite folder already exists!"); /* r1 */
define('_SUBSITES_CREATE_ERROR', "Cannot create subsite folder"); /* r1 */
define('_SUBSITES_CLONE', "Subsite will be cloned from %s %s"); /* r1, sprintf */
define('_SUBSITES_REMEMBER', "Remember that the new subsite will be offline by default"); /* r1 */
define('_SUBSITES_SUBSITE', "Subsite"); /* r1 */
define('_SUBSITES_ROOT', "Root site"); /* r1 */
define('_SUBSITES_CREATED', "Subsite successfully created"); /* r1 */
define('_SUBSITES_ACCEED', "Click here to access to the administrative area of "); /* r451 */
define('_SUBSITES_UPDATE_CONFIRM', "Proceed to update subsite database?"); /* r1 */
define('_SUBSITE_FATAL_ERROR', "Fatal error"); /* r1 */
define('_SUBSITE_ANCIENT', "The subsite was installed with Lanius CMS < v0.4.8, hence it is not supported. Read more at the Lanius CMS official website."); /* r1 */
define('_SUBSITE_UP_TO_DATE', "Subsite is up to date"); /* r1 */
define('_SUBSITE_UPDATE', "Subsite update"); /* r1 */
define('_SUBSITE_NOTHING_TO_DO', "No operation has been performed on the database of subsite &quot;%s&quot;."); /* r1, sprintf */
define('_SUBSITES_SAME_PREFIX', "You are not allowed to create a subsite with the same table prefix of the root site when not using a flatfile database."); /* r1 */
define('_SUBSITES_CLEAN', "Freshly installed subsite"); /* r1 */
?>