<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SYNDICATE_RSS_2_0_ENABLED', "RSS 2.0 enabled"); /* r1 */
define('_SYNDICATE_ATOM_1_0_ENABLED', "ATOM 1.0 enabled"); /* r1 */
define('_SYNDICATE_RSS_1_0_ENABLED', "RSS 1.0 enabled"); /* r1 */
define('_SYNDICATE_DEFAULT_FEED_TYPE', "Default feed type"); /* r1 */
define('_SYNDICATE_RSS_2_0', "RSS 2.0"); /* r1 */
define('_SYNDICATE_ATOM_1_0', "ATOM 1.0"); /* r1 */
define('_SYNDICATE_RSS_1_0', "RSS 1.0"); /* r1 */
define('_SYNDICATE_ATOM_CHANNEL_TITLE', "Title for ATOM channel"); /* r1 */
define('_SYNDICATE_ATOM_CHANNEL_AUTHOR', "Author for ATOM channel"); /* r1 */
define('_SYNDICATE_ATOM_CHANNEL_MAIL', "Email address for ATOM channel"); /* r1 */
?>