<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SYSTEM_LOG_ENTRIES', "Lanius CMS log file entries"); /* r1 */
define('_SYSTEM_DOWNLOAD', "Download"); /* r1 */
define('_SYSTEM_SELECT_ONE', "Select one SQL input file"); /* r1 */
define('_SYSTEM_REMOTE_VERSION', "Latest Lanius CMS release"); /* r1 */
define('_SYSTEM_NEED_UPDATE', "You have an older version of Lanius CMS and are invited to update it"); /* r1 */
define('_SYSTEM_UP_TO_DATE', "Your Lanius CMS installation is up to date with the latest official release"); /* r1 */
define('_SYSTEM_CACHED_UPDATE', "Your cached updates file was downloaded on"); /* r1 */
define('_SYSTEM_UPDATE_NOTICE', "To get the latest updates, click on"); /* r1 */
define('_SYSTEM_NO_UPDATES', "No update items, click Update to check from the online server"); /* r1 */
define('_SYSTEM_UNKNOWN', "You are using an SVN revision of Lanius CMS"); /* r1 */
define('_SYSTEM_TITLE', "System"); /* r1 */
define('_SYSTEM_TARGET', "Target"); /* r1 */
define('_SYSTEM_REP_HEAD', "Lanius CMS online updates"); /* r1 */
define('_SYSTEM_CLEAR', "Clear"); /* r1 */
define('_SYSTEM_CANNOT_RETRIEVE_UPDATES', "Cannot retrieve updates from remote or local source"); /* r1 */
define('_SYSTEM_CANNOT_RETRIEVE_SERVLET', "Cannot retrieve %s"); /* r1 */
define('_SYSTEM_PROCEED', "Proceed"); /* r1 */
define('_SYSTEM_INSTTOOL_TEXT', "This page allows to uninstall or reinstall Lanius CMS automatically.\n\nBe careful! You must know what you are doing before proceeding.\n\nEnter DROPALL to drop all currently active database tables and delete config.php\n\nEnter REMALL to eradicate all files and directories without touching the database \n\nEnter REINSTALL to drop the tables and reinstall them as in a new installation\n\nEnter UNINSTALL to drop all currently active database tables and eradicate all files and directories (equivalent of a DROPALL action followed by a REMALL action)"); /* r653 */
define('_SYSTEM_DROPALL_HEAD', "Drop all CMS tables"); /* r1 */
define('_SYSTEM_DROPALL_TEXT', "This action will drop all tables associated with the currently active database and will remove config.php to allow a manual reinstallation.\n\nNOTE: you should already have removed the subsites before proceeding, or else they will be orphaned"); /* r1 */
define('_SYSTEM_REMALL_HEAD', "Remove all files under CMS directory"); /* r1 */
define('_SYSTEM_REMALL_TEXT', "This action will remove all files under the CMS directory (both Lanius CMS source and any other user file).\n\nIf there are subsites, they will be removed too but you are invited to delete them manually because if some of them does not have a flatfile database its tables will be orphaned."); /* r1 */
define('_SYSTEM_REINSTALL_HEAD', "Reinstall Lanius CMS"); /* r1 */
define('_SYSTEM_REINSTALL_TEXT', "REINSTALL"); /* r1 */
define('_SYSTEM_UNINSTALL_HEAD', "Uninstall Lanius CMS"); /* r1 */
define('_SYSTEM_UNINSTALL_TEXT', "UNINSTALL"); /* r1 */
define('_SYSTEM_INVALID_XML', "Invalid XML file"); /* r910 */
define('_SYSTEM_INSTTOOL_ACTION', "Enter action here"); /* r1 */
define('_INSTALL_INSTOOL_GO_ON', "Click Proceed to perform these operations"); /* r1 */
define('_PACKAGES', "Packages"); /* r1 */
define('_SYSTEM_AUW', "Automatic update wizard"); /* r566 */
define('_SYSTEM_URL_ERROR', "'Could not retrieve %s"); /* r566, sprintf */
?>