<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_TEMPLATES_WRITE', "Writable"); /* r1 */
define('_TEMPLATES_NWRITE', "Not Writable"); /* r1 */
define('_TEMPLATES_EDIT', "Edit Template"); /* r1 */
define('_TEMPLATES_EDIT_HTML', "Edit XHTML"); /* r1 */
define('_TEMPLATES_EDIT_CSS', "Edit template CSS"); /* r1 */
define('_TEMPLATES_INFO', "Template Information"); /* r1 */
define('_TEMPLATES_INFO_ERROR', "Error reading template XML file"); /* r1 */
define('_EDIT_STATUS', "Path: %s is %s"); /* r1, sprintf */
?>