<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_USER_USERS', "Users"); /* r1 */
define('_USER_ACTIVE', "Active"); /* r1 */
define('_USERS_HEAD', "Manage Users"); /* r1 */
define('_USERS_UID', "User ID"); /* r1 */
define('_USERS_GRP', "Users Group"); /* r1 */
define('_USERS_NEW_HEAD', "New User"); /* r1 */
define('_USERS_EDIT_HEAD', "Edit User"); /* r1 */
define('_USER_ACTIVATE', "Activate"); /* r1 */
define('_USER_DEACTIVATE', "Deactivate"); /* r1 */
define('_USER_PASSWORD_DESC', "Leave the password field empty to preserve the previous password"); /* r1 */
define('_USER_PASSWORD_CONFIRM', "Password confirmation"); /* r170 */
define('_USER_ALLOW_DELETE_FE', "Allow deletion of user profile from frontend"); /* r439 */
define('_ADMIN_USER_ORIG_PASS_MISMATCH', "Original password does not match!"); /* r170, raw */
define('_USER_INFO_MIN_GID', "Minimum group level to show profile info"); /* r626 */
?>