<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_WEBLINKS_HIDE_HITS', "Hide hits count"); /* r1005 */
?>