<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_WRAPPER_SCROLLING', "Scrolling"); /* r1 */
define('_WRAPPER_AUTO', "Auto"); /* r1 */
define('_SHOW_PAGE_TITLE', "Show page title"); /* r1 */
define('_FRAME_HEIGHT', "Height of the frame/div (0 to leave unspecified)"); /* r1 */
define('_FRAME_WIDTH', "Width of the frame/div (0 to leave unspecified)"); /* r1 */
define('_INCLUDE_MODE', "Include mode"); /* r1 */
define('_PHP_INCLUDE', "Include as a PHP script"); /* r1 */
define('_RAW_FILE', "Include the raw file"); /* r1 */
define('_PRE_BLOCK', "Include the raw file in a &lt;pre /&gt; block"); /* r1 */
define('_USE_IFRAME', "Include into an IFRAME"); /* r1 */
?>