<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_INSTALL_INSTALLATION', "Installation"); /* r1 */
define('_INSTALL_STAGE', "Stage"); /* r895 */
define('_INSTALL_LICENSE', "Lanius CMS is Free Software released under the"); /* r1 */
define('_INSTALL_READ_LICENSE', "You must read and accept the terms and conditions expressed in the below license before continuing."); /* r1 */
define('_INSTALL_LICENSE_AGREE', "I have read the license and agree."); /* r1 */
define('_INSTALL_PRECHECK_WELCOME', "Welcome to Lanius CMS Install Wizard"); /* r1 */
define('_INSTALL_PRECHECK_INSTALL', "This wizard will guide you through Lanius CMS install process and will require only a few minutes to have a running Lanius CMS."); /* r1 */
define('_INSTALL_TEAM', "The Lanius CMS Team"); /* r1 */
define('_INSTALL_CONTINUE', "Click here to continue"); /* r1 */
define('_INSTALL_0_PATH', "Website folder (server)"); /* r1 */
define('_INSTALL_SERVER', "PHP configuration check"); /* r1 */
define('_INSTALL_SETTING_BAD', "PHP setting %s is set %s"); /* r1, sprintf */
define('_INSTALL_0_WRITE', "Writable"); /* r1 */
define('_INSTALL_1_CHANGED', "Changed to writable"); /* r1 */
define('_INSTALL_1_EMAIL_SETTINGS', "Email settings"); /* r1033 */
define('_INSTALL_1_EMAIL_SETTINGS_DESC', "Lanius CMS allows some basic messaging and notification system through emails. It is important to specify a valid reliable recipient in order to allow mail transfer agents to correctly signal an undelivered message, and to allow users track back the originating system."); /* r1033 */
define('_INSTALL_1_FROM_ADDRESS', "Reliable email address for returned emails and direct replies"); /* r1033 */
define('_INSTALL_1_FROM_NAME', "Reliable name associated to above email address"); /* r1033 */
define('_INSTALL_0_NWRITE', "Not writable (check also subfolders)"); /* r1 */
define('_INSTALL_1_ERROR', "Some folders were not writable and no other writable folder was found in the root path.\n\nIf you can modify the write permissions manually (through a remote/local shell or FTP, see %s for more information) please cancel this installation procedure and run it again when write permissions have been changed, otherwise you can proceed anyway without the features mentioned in the above column &quot;Writability purpose&quot; where &quot;Status&quot; is not writable.\n\nFlat file databases (Gladius DB or SQLite) will not be available because they need write permissions on the database file(s)."); /* r1, sprintf */
define('_INSTALL_READ_ONLY_CONTINUE', "Continue anyway without the above functionalities"); /* r1 */
define('_INSTALL_PERMELEV_FTP', "Lanius CMS has identified folder %s to have enough write permissions. You can use your FTP client to upload files there and then move them back in the correct folders."); /* r1, sprintf */
define('_INSTALL_1_MAIN', "General configuration setup "); /* r1 */
define('_INSTALL_1_MAIN_EXP', "General configuration required to start a new Lanius CMS installation. You can later access these settings from the admin backend selecting System -&gt; Global configuration from the menu."); /* r1 */
define('_INSTALL_1_URL', "Website URL (including the root path)"); /* r1 */
define('_INSTALL_1_TITLE', "Website Title"); /* r1 */
define('_INSTALL_1_ADMIN', "Administration account setup"); /* r1 */
define('_INSTALL_1_ADMIN_EXP', "Note down the admin username and password"); /* r1 */
define('_INSTALL_1_NAME', "Extended admin name"); /* r1 */
define('_INSTALL_1_USERNAME', "Username"); /* r1 */
define('_INSTALL_1_PASSWORD', "Password"); /* r1 */
define('_INSTALL_1_EMAIL', "Administrator email"); /* r1 */
define('_INSTALL_3_CONFIG_EXP', "The main configuration file where global Lanius CMS settings are stored in."); /* r1 */
define('_INSTALL_3_CONFIG_WRITE', "Writing configuration file"); /* r1 */
define('_INSTALL_3_CONFIG_ERROR', "Unwriteable - Create config.php from below text"); /* r1 */
define('_INSTALL_3_DB_SETTINGS', "Database settings"); /* r1 */
define('_INSTALL_3_DB_ERROR', "Could not connect to database, please check settings."); /* r1 */
define('_INSTALL_3_SUCCESS', "Successful"); /* r1 */
define('_INSTALL_5_ERRORS', "Errors found"); /* r1 */
define('_INSTALL_5_CONFIG_CONTENT', "Please manually create %s with the following content"); /* r1, sprintf */
define('_INSTALL_3_DB', "Database setup"); /* r1 */
define('_INSTALL_3_DB_WRITE', "Database creation"); /* r1 */
define('_INSTALL_3_CFG_TEMPLATE', "Database settings will be read from config.template.php"); /* r1 */
define('_INSTALL_5_SUCCESS', "Installation successful."); /* r1 */
define('_INSTALL_5_FAILURE', "Failure"); /* r1 */
define('_INSTALL_3_EXITUS', "Final results"); /* r1 */
define('_INSTALL_3_FRONT', "FrontPage"); /* r1 */
define('_INSTALL_3_ADMIN', "Admin backend"); /* r1 */
define('_INSTALL_3_DB_CREATE_ERR', "Cannot create database folder"); /* r1 */
define('_INSTALL_GPL', "GNU General Public License"); /* r1 */
define('_REINSTALLATION', "Re-installation"); /* r1 */
define('_REINSTALL_MSG', "You are trying to install over a previous installation"); /* r1 */
define('_REINSTALL_ADVICE', "Delete the %s file (or rename it to config.template.php if you wish to use the previous settings) in order to continue"); /* r1, sprintf */
define('_INSTALL_SAFE_MODE_DISCLAIM', "Some system and/or filesystem operations may not be allowed"); /* r1 */
define('_INSTALL_FILE_UPLOADS_DISCLAIM', "The contact component will not be able to deliver the attachments, installation via upload will not be possible and other upload related limitations"); /* r1 */
define('_INSTALL_MQGPC_DISCLAIM', "Lanius CMS does not need this weak security mechanism, possible slowdown in all operations"); /* r1 */
define('_INSTALL_MQRT_DISCLAIM', "Your PHP scripts will be slown down and may not work at all"); /* r1 */
define('_INSTALL_RG_DISCLAIM', "A very dangerous security threat! Lanius CMS will not offer security holes but your other PHP scripts might!"); /* r1 */
define('_INSTALL_SAS_DISCLAIM', "Lanius CMS will not start the session when needed, as it will be always started (trivial)"); /* r1 */
define('_INSTALL_1_WRITABILITY_PURPOSE', "Writability Purpose"); /* r1 */
define('_INSTALL_1_STATUS', "Status"); /* r1 */
define('_INSTALL_1_UPDATE_FEATURE', "Update feature"); /* r1 */
define('_INSTALL_1_COMPONENTS_INSTALLATION', "Components installation"); /* r1 */
define('_INSTALL_1_DRABOTS_INSTALLATION', "Drabots installation"); /* r1 */
define('_INSTALL_1_MODULES_INSTALLATION', "Modules installation"); /* r1 */
define('_INSTALL_1_TEMPLATES_INSTALLATION', "Templates installation"); /* r1 */
define('_INSTALL_1_LANGUAGES_INSTALLATION', "Languages installation"); /* r1 */
define('_INSTALL_1_BACKUPS', "Database and tarball backups"); /* r1 */
define('_INSTALL_1_GALLERY', "Gallery component"); /* r1 */
define('_INSTALL_1_PHP_CONF', "PHP configuration"); /* r895 */
define('_INSTALL_1_REQ_NOT_MET', "Your PHP installation does not meet the minimal requirements."); /* r895 */
define('_INSTALL_1_MIN_REQ_NOT_MET', "Minimal requirements not satisfied."); /* r895 */
define('_INSTALL_5_DATABASE_CONNECTION', "Database connection"); /* r1 */
define('_INSTALL_5_DATABASE_CONNECTION_PROGRESS', "Connecting to database..."); /* r1 */
define('_INSTALL_5_DATABASE_FOLDER_PERMS', "Database folder permissions"); /* r1 */
define('_INSTALL_5_DATABASE_FOLDER_PERMS_DESC', "You are using a flatfile database, its folder %s needs write permissions"); /* r1, sprintf */
define('_INSTALL_5_DATABASE_FOLDER_PERMS_PROGRESS', "Testing write permissions"); /* r1 */
define('_INSTALL_5_DATABASE_FOLDER', "Database folder"); /* r1 */
define('_INSTALL_5_DATABASE_FOLDER_DESC', "A folder named as the database must exist in the %s site subfolder"); /* r1, sprintf */
define('_INSTALL_5_DATABASE_FOLDER_PROGRESS', "Asserting existance of folder for database %s"); /* r1, sprintf */
define('_INSTALL_5_DATABASE_FOLDER_FAILURE', "Cannot create the folder for the flatfile database"); /* r1 */
define('_ON', "On"); /* r1 */
define('_OFF', "Off"); /* r1 */
define('_INSTALL_DIRECTIVE', "Directive"); /* r1 */
define('_INSTALL_ACTUAL', "Actual"); /* r1 */
define('_INSTALL_RECCOMENDED', "Recommended"); /* r1 */
define('_INSTALL_PHP_VERSION_CHECK', "PHP version check"); /* r1 */
define('_INSTALL_PHP_VERSION_CHECK_DESC', "PHP version above or equal to %s (v%s < v%s not supported)"); /* r1, sprintf */
define('_INSTALL_GPL_AGREE_MSG', "You have not agreed with the GPL license"); /* r1, raw */
?>