<?php if(!defined('_VALID')){header('Status: 404 Not Found');die;}
## FCKEditor implementation
# @author legolas558
#

$_DRABOTS->registerFunction( 'OnEditor', 'botFCKEditor' );

$_DRABOTS->registerFunction( 'OnContentEdit', 'botFixFCKpath_edit' );

//$_DRABOTS->registerFunction( 'OnContentSave', 'botFixFCKpath_save' );

//$_DRABOTS->registerFunction( 'OnEditorSaveJS', 'botFCKEditorSaveJS' );

$_DRABOTS->registerFunction( 'OnEditorSaveAll', 'botFCKEditorSaveAll' );

function FCKeditor_IsCompatibleBrowser()
{
	if ( isset( $_SERVER ) ) {
		$sAgent = $_SERVER['HTTP_USER_AGENT'] ;
	}
	else {
		global $HTTP_SERVER_VARS ;
		if ( isset( $HTTP_SERVER_VARS ) ) {
			$sAgent = $HTTP_SERVER_VARS['HTTP_USER_AGENT'] ;
		}
		else {
			global $HTTP_USER_AGENT ;
			$sAgent = $HTTP_USER_AGENT ;
		}
	}

	if ( strpos($sAgent, 'MSIE') !== false && strpos($sAgent, 'mac') === false && strpos($sAgent, 'Opera') === false )
	{
		$iVersion = (float)substr($sAgent, strpos($sAgent, 'MSIE') + 5, 3) ;
		return ($iVersion >= 5.5) ;
	}
	else if ( strpos($sAgent, 'Gecko/') !== false )
	{
		$iVersion = (int)substr($sAgent, strpos($sAgent, 'Gecko/') + 6, 8) ;
		return ($iVersion >= 20030210) ;
	}
	else if ( strpos($sAgent, 'Opera/') !== false )
	{
		$fVersion = (float)substr($sAgent, strpos($sAgent, 'Opera/') + 6, 4) ;
		return ($fVersion >= 9.5) ;
	}
	else if ( preg_match( "|AppleWebKit/(\d+)|i", $sAgent, $matches ) )
	{
		$iVersion = $matches[1] ;
		return ( $matches[1] >= 522 ) ;
	}
	else
		return false ;
}

class FCKeditor
{
	var $InstanceName ;
	var $BasePath ;
	var $Width ;
	var $Height ;
	var $ToolbarSet ;
	var $Value ;
	var $Config ;

	function FCKeditor( $instanceName )
	{
		$this->InstanceName	= $instanceName ;
		$this->BasePath		= '/fckeditor/' ;
		$this->Width		= '100%' ;
		$this->Height		= '200' ;
		$this->ToolbarSet	= 'Default' ;
		$this->Value		= '' ;

		$this->Config		= array() ;
	}

	function Create()
	{
		echo $this->CreateHtml() ;
	}

	function CreateHtml()
	{
		$HtmlValue = htmlspecialchars( $this->Value ) ;

		$Html = '' ;

		if ( !isset( $_GET ) ) {
			global $HTTP_GET_VARS ;
			$_GET = $HTTP_GET_VARS ;
		}

		if ( $this->IsCompatible() )
		{
			if ( isset( $_GET['fcksource'] ) && $_GET['fcksource'] == "true" )
				$File = 'fckeditor.original.html' ;
			else
				$File = 'fckeditor.html' ;

			$Link = "{$this->BasePath}editor/{$File}?InstanceName={$this->InstanceName}" ;

			if ( $this->ToolbarSet != '' )
				$Link .= "&amp;Toolbar={$this->ToolbarSet}" ;

			// Render the linked hidden field.
			$Html .= "<input type=\"hidden\" id=\"{$this->InstanceName}\" name=\"{$this->InstanceName}\" value=\"{$HtmlValue}\" style=\"display:none\" />" ;

			// Render the configurations hidden field.
			$Html .= "<input type=\"hidden\" id=\"{$this->InstanceName}___Config\" value=\"" . $this->GetConfigFieldString() . "\" style=\"display:none\" />" ;

			// Render the editor IFRAME.
			$Html .= "<iframe id=\"{$this->InstanceName}___Frame\" src=\"{$Link}\" width=\"{$this->Width}\" height=\"{$this->Height}\" frameborder=\"0\" scrolling=\"no\"></iframe>" ;
		}
		else
		{
			if ( strpos( $this->Width, '%' ) === false )
				$WidthCSS = $this->Width . 'px' ;
			else
				$WidthCSS = $this->Width ;

			if ( strpos( $this->Height, '%' ) === false )
				$HeightCSS = $this->Height . 'px' ;
			else
				$HeightCSS = $this->Height ;

			$Html .= "<textarea name=\"{$this->InstanceName}\" rows=\"4\" cols=\"40\" style=\"width: {$WidthCSS}; height: {$HeightCSS}\">{$HtmlValue}</textarea>" ;
		}

		return $Html ;
	}

	function IsCompatible()
	{
		return FCKeditor_IsCompatibleBrowser() ;
	}

	function GetConfigFieldString()
	{
		$sParams = '' ;
		$bFirst = true ;

		foreach ( $this->Config as $sKey => $sValue )
		{
			if ( $bFirst == false )
				$sParams .= '&amp;' ;
			else
				$bFirst = false ;

			if ( $sValue === true )
				$sParams .= $this->EncodeConfig( $sKey ) . '=true' ;
			else if ( $sValue === false )
				$sParams .= $this->EncodeConfig( $sKey ) . '=false' ;
			else
				$sParams .= $this->EncodeConfig( $sKey ) . '=' . $this->EncodeConfig( $sValue ) ;
		}

		return $sParams ;
	}

	/**
	 * Encode characters that may break the configuration string
	 * generated by GetConfigFieldString().
	 *
	 * @access protected
	 * @param string $valueToEncode
	 * @return string
	 */
	function EncodeConfig( $valueToEncode )
	{
		$chars = array(
			'&' => '%26',
			'=' => '%3D',
			'"' => '%22' ) ;

		return strtr( $valueToEncode,  $chars ) ;
	}
} // end of FCKeditor class

global $d,	$d_website, $d_subpath, $_DRABOTS, $my;

function _FCK_map_language($lang) {
	global $d_root;
	
	// some alias conversions
	$aliases = array( 'cn' => 'zh-cn', 'br' => 'pt-br',
					'ca' => 'fr-ca', 'uk' => 'en-uk', 'au' => 'en-au'
//					, '??' => 'en-ca', '??' => 'sr-latn' 
					);
	
	if (isset($aliases[$lang]))
		$lang = $aliases[$lang];
	
	if (file_exists($d_root.'editor/fckeditor/editor/lang/'.$lang.'.js'))
		return $lang;
	global $d_deflang;
	return $d_deflang;
}


$dparams = $_DRABOTS->GetBotParameters('editor', 'fckeditor');
$d->add_js('editor/fckeditor/fckeditor.js');
	$d->add_raw_js('
	var FCKeditors = new Array();
	var FCKtotal=0;
	function FCKsave(){
		for (i = 0; i < FCKeditors.length; i++) {
  	 		var oEditor = FCKeditorAPI.GetInstance(FCKeditors[i]);
  	 		document.getElementById(FCKeditors[i]).value = oEditor.GetHTML() ;
		}
	}

	function FCK_rel_path() { return "../../../../'.$d->SubsitePath().'"; }
	
	function FCK_skin() { return "'.js_encode($dparams->get('skin', 'silver')).'"; }
	
	function FCK_lang() { return "'.js_encode(_FCK_map_language($my->lang)).'"; }

	function FCK_new_instance(name) {
		var oFCKeditor = new FCKeditor(name);
		oFCKeditor.BasePath = \''.$d_subpath.'editor/fckeditor/\';
		oFCKeditor.Height = \'400\';
		oFCKeditor.ReplaceTextarea() ;
		FCKeditors[FCKtotal]=name;
		++FCKtotal;
	}
	');
	
function botFCKEditor($d_name, $value, $row, $cols, $extra) {
	$eEditor = "eEditor".$d_name;
	return "<div id=\"$eEditor\">
<textarea name=\"$d_name\" id=\"$d_name\" cols=\"$cols\" rows=\"$row\">$value</textarea>
</div>
<script type=\"text/javascript\">
FCK_new_instance('$d_name');
</script>";
}

/*function botFCKEditorSaveJS($area_name) {
	return "FCKsave();";
}*/

function botFCKEditorSaveAll() {
	return "FCKsave();";
}

function __FCK_replace_url_abs($m) {
	if (is_url($m[2]))
		return $m[0];
	global $d_website;
	return $m[1].'="'.$d_website.$m[2].'"';
}

function _FCK_tag_fix_abs($m) {
	return preg_replace_callback('/(href|src)="?([^"\\s>]+)"?/i', '__FCK_replace_url_abs', $m[0]);
}

function botFixFCKpath_edit(&$content) {
	$content = preg_replace_callback('/<\\w+\\s+[^>]+>/s', '_FCK_tag_fix_abs', $content);
}

?>
