<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_NEWSFEED_LINK', "Newsfeed URL"); /* r170 */
define('_NEWSFEED_ITEMS', "Number of items to show"); /* r1 */
define('_NEWSFEED_REFRESH', "Time before the feed is refetched"); /* r1 */
define('_NEWSFEED_FETCH_ERROR', "Error fetching feed URL"); /* r1 */
?>