<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_GETFF_SHOW_FILTER', "Show icon to"); /* r170 */
define('_GETFF_SHOW_ALL', "All browsers"); /* r170 */
define('_GETFF_SHOW_ALLNG', "All browsers except Mozilla/Gecko-based"); /* r170 */
define('_GETFF_SHOW_IE', "All IE-based browsers"); /* r170 */
define('_GETFF_MSG', "Default message under Get Firefox icon"); /* r1 */
?>