<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_POLL_NO', "Could not show poll"); /* r1 */
define('_POLL_ID', "Poll ID (use 0 to randomly select a poll)"); /* r170 */
define('_BUTTON_VOTE', "Vote"); /* r1 */
?>