<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_LOGIN_HI', "Hi"); /* r1 */
define('_LOGIN_ENTER_USERNAME', "Please fill the username field"); /* r1 */
define('_LOGIN_ENTER_PASSWORD', "Please fill the password field"); /* r1 */
?>