<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SEARCH_BOX', "Search..."); /* r1 */
define('_SEARCH_WIDTH', "Search box width"); /* r1 */
define('_SEARCH_TEXT_Q', "Search box default text"); /* r1 */
?>