<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MODWRAPPER_LINK', "Relative or full URL, or wrapper menu item id (numeric)"); /* r1 */
?>