<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SORT_BY', "Sort by"); /* r1 */
define('_TOP_DOWNLOADS', "Top downloads"); /* r1 */
define('_LAST_DOWNLOADS', "Last downloads"); /* r1 */
define('_TOP_RATED', "Top rated"); /* r1 */
define('_NEW_DOWNLOADS', "New downloads"); /* r1 */
?>