<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_VALIDATE_XHTML', "XHTML validation"); /* r1 */
define('_VALIDATE_XHTML_VERSION', "XHTML version caption"); /* r1 */
define('_VALIDATE_CSS', "CSS validation"); /* r1 */
define('_VALIDATE_CSS_VERSION', "CSS version caption"); /* r1 */
?>