<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MENU_NAME', "Menu name"); /* r1 */
define('_MENU_STYLE', "Menu style"); /* r1 */
define('_MENU_NAME_DESC', "The name of the menu (default is 'mainmenu')"); /* r1 */
define('_MENU_CLASS_SUFFIX', "Menu class suffix"); /* r1 */
define('_MENU_CLASS_SUFFIX_DESC', "A suffix to be applied to the CSS class of the menu items"); /* r1 */
define('_MENU_VERTICAL', "Vertical"); /* r1 */
define('_MENU_HORIZONTAL', "Horizontal"); /* r1 */
define('_MENU_FLAT', "Flat list"); /* r1 */
?>