<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SHOW_DESCRIPTION', "Show description"); /* r1 */
define('_COUNT_DESC', "The number of items to display (default is 10)"); /* r1 */
define('_POPULAR_CONTENT_CATEGORY', "Content category"); /* r1 */
define('_POPULAR_CONTENT_SECTION', "Content section (overrides category)"); /* r1 */
define('_POPULAR_CONTENT_SECTION_DESC', "Select the most popular items from categories of a specific content section"); /* r1 */
define('_POPULAR_CONTENT_CATEGORY_DESC', "Select the most popular items from a specific content category"); /* r1 */
?>