<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_TIME_STAT', "Time"); /* r1 */
define('_MEMBERS_STAT', "Members"); /* r1 */
define('_HITS_STAT', "Visits today"); /* r1 */
define('_NEWS_STAT', "News"); /* r1 */
define('_LINKS_STAT', "Weblinks"); /* r1 */
define('_STATS_VISITORS', "Total visits"); /* r1 */
?>