<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SHOW_DD', "Show label for drop down of names"); /* r1 */
define('_SHOW_TYPE', "Appearance of language selector"); /* r1 */
define('_SHOW_TYPE_DESC', "Define how the selector should be generated."); /* r1 */
define('_DD_NAMES', "Drop down of names"); /* r1 */
define('_SHOW_FLAGS', "Flags"); /* r1 */
?>