<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_LATEST_NEWS_SHOW_DESCRIPTION', "Show description"); /* r1 */
define('_LATEST_NEWS_COUNT_DESC', "The number of items to display (default 5)"); /* r1 */
define('_LATEST_NEWS_CONTENT_CATEGORY', "Content category"); /* r1 */
define('_LATEST_NEWS_CONTENT_CATEGORY_DESC', "Select latest items from a specific category"); /* r1 */
define('_LATEST_NEWS_COLUMNS_COUNT', "Number of columns to use"); /* r1 */
define('_LATEST_NEWS_CONTENT_SECTION', "Content section (overrides category)"); /* r1 */
define('_LATEST_NEWS_CONTENT_SECTION_DESC', "Select the latest news from categories of a specific content section"); /* r1 */
?>