<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_STREAM_RENDERER', "Renderer of the media stream"); /* r1 */
define('_RENDERER_DESC', "Choose the media stream rendering player"); /* r1 */
define('_STREAM_URL', "Stream URL or local path"); /* r1 */
define('_HIDE_PLAYER', "Hide Player"); /* r1 */
define('_STREAM_WIDTH', "Width"); /* r1 */
define('_STREAM_HEIGHT', "Height"); /* r1 */
define('_STREAM_NO_FLASH', "Your browser cannot diplay the Flash media"); /* r895 */
define('_SHOW_CONTROLS', "Show controls"); /* r1 */
define('_AUTO_START', "Automatic start"); /* r1 */
define('_STREAM_WM', "Windows Media Player"); /* r1 */
define('_STREAM_QT', "Quicktime Player"); /* r1 */
define('_STREAM_FLASH', "Macromedia Flash Player"); /* r1 */
define('_STREAM_REAL', "RealPlayer"); /* r1 */
?>