<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_WHOSONLINE_WE_HAVE', "We have "); /* r1 */
define('_WHOSONLINE_AND', " and "); /* r1 */
define('_WHOSONLINE_GUEST', " guest"); /* r1 */
define('_WHOSONLINE_GUESTS', " guests"); /* r1 */
define('_WHOSONLINE_MEMBER', " member"); /* r1 */
define('_WHOSONLINE_MEMBERS', " members"); /* r1 */
define('_WHOSONLINE_ONLINE', " online"); /* r1 */
define('_WHOSONLINE_NONE', "No users online"); /* r1 */
?>