<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_ARCHIVE_COUNT_DESC', "The number of items to display (default is 10)"); /* r1 */
define('_NO_ARCHIVED_NEWS', "There are no archived news items"); /* r1 */
?>