<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_NEWSFLASH_CONTENT_CATEGORY', "Content category"); /* r1 */
define('_NEWSFLASH_CONTENT_CATEGORY_DESC', "Randomly select newsflash items from a specific category"); /* r1 */
?>