<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_BANNER_ID', "Banner ID ( leave empty in case of random banner )"); /* r1 */
define('_BANNER_JS_ROTATE', "Javascript rotation delay in seconds"); /* r1 */
define('_BANNER_JS_ROTATE_DESC', "If you have not specified a banner id and will specify the below seconds delay (0 will disable the feature), a javascript-based rotation mechanism will be used to rotate all the banners.\nNote: banner code or SWF banners will not be working in such case"); /* r1 */
?>