<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SMILEY_COOL', "cool"); /* r1 */
define('_SMILEY_WINK', "wink"); /* r1 */
define('_SMILEY_SMILE', "smile"); /* r1 */
define('_SMILEY_TONGUE', "tongue"); /* r1 */
define('_SMILEY_LAUGHING', "laughing"); /* r1 */
define('_SMILEY_SHOCKED', "shocked"); /* r1 */
define('_SMILEY_SICK', "sick"); /* r1 */
define('_SMILEY_ANGRY', "angry"); /* r1 */
define('_SMILEY_BLINK', "blink"); /* r1 */
define('_SMILEY_SAD', "sad"); /* r1 */
define('_SMILEY_UNSURE', "unsure"); /* r1 */
define('_SMILEY_KISSING', "kissing"); /* r1 */
define('_SMILEY_W00T', "w00t"); /* r1 */
define('_SMILEY_GRIN', "grin"); /* r1 */
define('_SMILEY_SILLY', "silly"); /* r1 */
define('_SMILEY_PINCH', "pinch"); /* r1 */
define('_SMILEY_SIDEWAYS', "sideways"); /* r1 */
define('_SMILEY_WHISTLING', "whistling"); /* r1 */
define('_SMILEY_DEVIL', "devil"); /* r1 */
define('_SMILEY_DIZZY', "dizzy"); /* r1 */
define('_SMILEY_BLUSH', "blush"); /* r1 */
define('_SMILEY_CHEERFUL', "cheerful"); /* r1 */
define('_SMILEY_WASSAT', "wassat"); /* r1 */
define('_SMILEY_ERMM', "ermm"); /* r1 */
?>