<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FS_WRITE_ACCESS_DENIED', "Write access denied"); /* r1 */
define('_FS_WRITE_FAILURE', "Failed to write to file"); /* r1 */
define('_FS_FAILURE_EXPLANATION', "If you cannot solve the error by its message, check that the correct write permissions are set on the target path"); /* r1 */
define('_FS_CONTACT_ADMIN', "Contact the system administrator and complain about this error"); /* r1 */
define('_FS_OPERATION_FAILED', "Filesystem operation failed"); /* r1 */
define('_FS_MKDIR_FAILURE', "Failed to create directory"); /* r1 */
define('_FS_COPY_FAILURE', "Failed to copy file"); /* r1 */
define('_FS_MOVE_FAILURE', "Failed to move file"); /* r1 */
define('_FS_REMOVE_FAILURE', "Failed to remove file"); /* r1 */
define('_FS_DIR_NOT_FOUND', "Directory not found"); /* r1 */
define('_FS_CANNOT_READ_UPLOAD', "Unable to read contents of uploaded file"); /* r170 */
define('_FS_RMDIR_FAILURE', "Failed to remove directory"); /* r1 */
define('_FS_CHMOD_FAILURE', "Failed to change mode (chmod)"); /* r1 */
define('_FS_CHGRP_FAILURE', "Failed to change group (chgrp)"); /* r1 */
define('_FS_FILES_WITHIN_FOLDER', "because it contains files, use ::deldir() instead"); /* r1 */
define('_FS_SRC_TO_DST', "%s to %s"); /* r1, sprintf */
?>