<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DATABASE', "Database"); /* r1 */
define('_FRONTPAGE', "Frontpage"); /* r1 */
define('_INSTALLED', "Installed"); /* r1 */
define('_TYPE', "Type"); /* r1 */
define('_GENERAL', "General"); /* r1 */
define('_CORE', "Core"); /* r1 */
define('_MDATE', "Date modified"); /* r1 */
define('_CDATE', "Date created"); /* r1 */
define('_DOWNLOAD', "Download"); /* r1 */
define('_REORDER', "Reorder"); /* r1 */
define('_INSTALL', "Install"); /* r1 */
define('_UNINSTALL', "Uninstall"); /* r1 */
define('_UPDATE_WIZARD', "Information about the latest version available, click to start the automatic update wizard"); /* r1 */
define('_ID', "ID"); /* r1 */
define('_INFO', "Info"); /* r1 */
define('_VER', "Version"); /* r1 */
define('_WEBSITE', "Website"); /* r1 */
define('_CMS_LICENSED', "Lanius CMS is Free Software released under the"); /* r1 */
define('_GPL', "GNU/GPL License"); /* r1 */
define('_INVALID_ID', "Specified ID is not valid"); /* r1 */
define('_CONTENT_CAT_HEAD', "Manage Categories"); /* r1 */
define('_CONTENT_MANAGE_CATEGORIES', "Manage categories in %s section"); /* r1 */
define('_CONTENT_CAT_NEW_HEAD', "New Category"); /* r1 */
define('_CONTENT_CAT_EDIT_HEAD', "Edit Category"); /* r1 */
define('_TEMPLATES_HEAD', "Templates manager"); /* r1 */
define('_DRABOTS', "Drabots"); /* r1 */
define('_DRABOTS_INSTALL', "Install Drabot"); /* r1 */
define('_MODULES', "Modules"); /* r1 */
define('_MODULES_INSTALL', "Install Module"); /* r1 */
define('_COMPONENTS_INSTALL', "Install Component"); /* r1 */
define('_COMPONENTS', "Components"); /* r1 */
define('_TEMPLATES', "Templates"); /* r1 */
define('_TEMPLATES_INSTALL', "Install Template"); /* r1 */
define('_CONFIG_SAVED', "Configuration was successfully saved"); /* r1 */
define('_CONTENT', "Content"); /* r1 */
define('_COMPONENTS_PARAMS', "Component Parameters"); /* r1 */
define('_MENU', "Menu"); /* r1 */
define('_MODULES_HEAD', "Modules manager"); /* r1 */
define('_DRABOTS_HEAD', "Drabots manager"); /* r1 */
define('_SYSTEM_VERSION_INFO', "Lanius CMS Version Information"); /* r1 */
define('_SYSTEM_PHP_INFO', "PHP Info"); /* r1 */
define('_SYSTEM_PATCHES', "Patches"); /* r1 */
define('_SYSTEM_TAR_BACKUP', "Tarball Backup"); /* r1 */
define('_IFC_FILTER_ERR', "The filter string can not be empty"); /* r1 */
define('_IFC_ERR', "Invalid value for"); /* r1 */
define('_IFC_DIGIT_ERR', "Invalid numerical value for"); /* r1 */
define('_IFC_LIST_ERR', "Please make a selection from the list first"); /* r1 */
define('_PLEASE_SELECT', "Please select at least %d items"); /* r1, sprintf */
define('_CUSTOM_CLASS', "Custom CSS class"); /* r1 */
define('_CUSTOM_CLASS_DESC', "The specified custom CSS class will be appended to the classes used to style the parent element"); /* r1 */
define('_IFC_CONFIRM', "Operation:\n\n%s\n\nAre you sure you want to proceed?"); /* r1, sprintf */
define('_IFC_OP_DELETE', "delete items"); /* r1 */
define('_IFC_OP_UNINSTALL', "uninstall items"); /* r1 */
define('_IFC_OP_REORDER', "reorder items"); /* r1 */
define('_IFC_FILTER_SHOW', "Show Filter"); /* r1 */
define('_IFC_FILTER_HIDE', "Hide Filter"); /* r1 */
define('_IFC_FILTER_DISABLE', "Disable Filter"); /* r1 */
define('_IFC_FILTER_GO', "Go"); /* r1 */
define('_IFC_CHECKBOX', "Select or deselect all items"); /* r542 */
define('_DB_QUERY', "Query database"); /* r1 */
define('_DB_BACKUP_HEAD', "Backup manager"); /* r1 */
define('_INSTALL_SUCCESS', "Install successfull"); /* r1 */
define('_INSTALL_FAILURE', "Installation failed"); /* r1 */
define('_INSTALL_FAILED_EXIST', "Install failure: already exists"); /* r1 */
define('_INSTALL_NO_INSTALLER', "Could not locate XML package descriptor"); /* r1 */
define('_INSTALL_NO_SOURCE', "No package source specified"); /* r1 */
define('_INSTALL_INVALID_URL', "Could not retrieve URL %s"); /* r1, sprintf, raw */
define('_INSTALL_INVALID', "XML package descriptor is not valid"); /* r1 */
define('_INSTALL_INVALID_VERSION', "Cannot install a package for version %s"); /* r1, sprintf */
define('_INSTALL_VERSION_NCOMPAT', "Version is not compatible"); /* r1, raw */
define('_INSTALL_VERSION_TOO_LOW', "A higher version is necessary"); /* r1, raw */
define('_INSTALL_INVALID_ARC', "Could not extract from archive\n\nPcl error:"); /* r1, raw */
define('_UNINSTALL_SUCCESS', "Uninstall successfull"); /* r1 */
define('_UNINSTALL_FAILED', "Uninstall procedure reported errors."); /* r1 */
define('_TB_NEW', "New"); /* r1 */
define('_TB_UPLOAD', "Upload"); /* r1 */
define('_TB_UPLOAD_GUI', "Upload (gui)"); /* r487 */
define('_TB_EDIT', "Edit"); /* r1 */
define('_TB_PUBLISH', "Publish"); /* r1 */
define('_TB_UNPUBLISH', "Un-Publish"); /* r1 */
define('_TB_ARCHIVE', "Archive"); /* r1 */
define('_TB_UNARCHIVE', "Un-Archive"); /* r1 */
define('_TB_CREATE', "Create"); /* r1 */
define('_TB_SAVE', "Save"); /* r1 */
define('_TB_BACK', "Back"); /* r1 */
define('_TB_REORDER', "Reorder"); /* r1 */
define('_UPLOAD_FILES', "Upload files"); /* r1 */
define('_INSTALL_FILE_DESC', "Retrieve installation files from archive or directory"); /* r1 */
define('_INSTALL_DIR_DESC', "Path to local directory containing extracted installation files"); /* r1 */
define('_LOCAL_DIR', "Local Path"); /* r1 */
define('_LOCAL_DIR_DESC', "Retrieve files from a local path"); /* r1 */
define('_REMOTE_URL', "Remote URL"); /* r1 */
define('_REMOTE_URL_DESC', "Enter the remote file URL"); /* r1 */
define('_FILE_UPLOAD', "File upload"); /* r1 */
define('_FILE_UPLOAD_DESC', "Upload a file from your computer"); /* r1 */
define('_UPLOAD_FILES_EXP', "Upload files to %s"); /* r1, sprintf */
define('_UPLOAD_FILES_EXT', "Allowed file extensions are: %s"); /* r1, sprintf */
define('_UPLOAD_SELECT', "Select Files"); /* r1 */
define('_FRONTPAGE_HEAD', "Frontpage manager"); /* r1 */
define('_LANG', "Languages"); /* r1 */
define('_LANG_EDIT_HEAD', "Edit language"); /* r1 */
define('_LANG_INFO_HEAD', "Language information"); /* r1 */
define('_LANG_INSTALL', "Install Language"); /* r1 */
define('_LANG_INFO_ERROR', "Error reading language XML file"); /* r1 */
define('_PATCHES', "Patches"); /* r1 */
define('_PATCHES_INSTALL', "Install Patch"); /* r1 */
define('_USERS_WEBLINKS', "Weblinks"); /* r1 */
define('_USERS_WEBLINKS_HEAD', "Weblinks manager"); /* r1 */
define('_USERS_WEBLINKS_NEW_HEAD', "New Weblink"); /* r1 */
define('_USERS_WEBLINKS_EDIT_HEAD', "Edit Weblink"); /* r1 */
define('_USERS_WEBLINKS_EDIT_CATEGORY', "Edit Weblink Category"); /* r1 */
define('_AMENU_MYSITE', "Settings"); /* r1 */
define('_AMENU_MYSITE_GCONFIG', "Global Configuration"); /* r1 */
define('_AMENU_MYSITE_TMANAGE_SITE', "Site Templates"); /* r1 */
define('_AMENU_MYSITE_TMANAGE_ADMIN', "Admin Templates"); /* r1 */
define('_AMENU_MYSITE_LMANAGE', "Language manager"); /* r1 */
define('_AMENU_MYSITE_LMANAGESITE', "Site Language"); /* r1 */
define('_AMENU_MYSITE_PREVIEW', "Preview in new page"); /* r1 */
define('_AMENU_MYSITE_FRONTEND', "Frontend"); /* r1 */
define('_AMENU_MYSITE_USERS_MANAGE', "Users manager"); /* r1 */
define('_AMENU_MYSITE_USERS_MAIL', "Mass Mail"); /* r1 */
define('_AMENU_INSTALL_TOOL', "Install / Uninstall Lanius CMS"); /* r1 */
define('_AMENU_MENU_MANGE', "Menus management"); /* r467 */
define('_AMENU_CONTENT_CAT', "Categories"); /* r1 */
define('_AMENU_CONTENT_ARCHIVE', "Archive"); /* r1 */
define('_AMENU_CONTENT_ITEMS', "Items"); /* r1 */
define('_AMENU_CONTENT_SECTIONS', "Add / Edit Sections"); /* r1 */
define('_AMENU_INST', "Install / Uninstall"); /* r1 */
define('_AMENU_MYADMIN', "My Admin"); /* r1 */
define('_AMENU_MYADMIN_HOME', "Home"); /* r1 */
define('_AMENU_COMPONENTS', "Components"); /* r1 */
define('_AMENU_CONTENTS', "Content"); /* r1 */
define('_AMENU_MODULES', "Modules"); /* r1 */
define('_AMENU_SYSTEM', "System"); /* r1 */
define('_AMENU_UPDATES', "Online updates"); /* r1 */
define('_AMENU_INSTALL_PATCH', "Install patch"); /* r1 */
define('_AMENU_HELP', "Help"); /* r1 */
define('_AMENU_HELP_ABOUT', "About"); /* r1 */
define('_AMENU_HELP_DOCUMENTATION', "Documentation"); /* r1 */
define('_AMENU_HELP_LICENSE', "License"); /* r1 */
define('_AMENU_SUBSITES', "Subsites"); /* r1 */
define('_AMENU_MANAGE_SUBSITES', "Subsites manager"); /* r1 */
define('_COMPONENTS_HEAD', "Components manager"); /* r1 */
define('_LOGIN_MSG2', "Invalid Username or Password entered"); /* r1 */
define('_LOGIN_REM', "Remember"); /* r1 */
define('_LOGIN_FORGOT', "I forgot the username or password"); /* r1 */
define('_SUPPORTED_FORMATS', "Supported Formats"); /* r1 */
define('_CLOSE', "Close"); /* r1 */
define('_BROWSE', "Browse"); /* r1 */
define('_COUNT', "Count"); /* r1 */
define('_DATE_FORMAT_EXTENDED', "%Y-%m-%d %H:%M:%S"); /* r1, special, raw */
define('_SHOW_COUNT', "Number of items to show"); /* r1 */
define('_SYSTEM_LOG', "Log"); /* r1 */
define('_NEW_SECTION', "New section"); /* r1 */
define('_WARNING_NOT_ENOUGH_TIME', "WARNING: your maximum execution time is too low and this operation might timeout!"); /* r1 */
define('_INSTALL_FAILURE_PATHS', "The paths of interest to this install file could not be set up"); /* r1 */
define('_INSTALL_NOTHING', "The specified source did not contain an installable fragment"); /* r1 */
define('_WARNING_CREATE_N_DOWNLOAD', "NOTE: since there are not enough write permissions for the %s directory, the created file will be automatically offered for download and not saved there."); /* r1, sprintf, raw */
define('_MOP_ACCESS', "Mass-reassign access group"); /* r1 */
define('_MOP_NO_CHANGE', "- No change -"); /* r1 */
define('_MOP_OWNER_CHANGE', "Change owner to"); /* r1 */
define('_MOP_OWNERSHIP_CHANGE', "User %s (#%d) changed ownership of element #%d in table %s from %s (#%d) to %s (#%d)"); /* r1, raw, sprintf */
define('_MOP_EXECUTE', "Execute"); /* r1 */
define('_MOP_EXECUTE_DESC', "Execute operations on all selected items"); /* r170 */
define('_MOP_INVERT_ORDER', "Invert order"); /* r1 */
define('_MOP_INVERT_ORDER_DESC', "Invert order of selected items (2 or more)"); /* r1 */
define('_ADMIN_DEFAULT_INSTANCE', "Default menu instance"); /* r1 */
define('_ADMIN_ALL_INSTANCES', "All menu instances"); /* r1 */
define('_ADMIN_TEST_DB', "Test database settings"); /* r1 */
define('_AMENU_INFORMATIONS', "Information"); /* r1 */
define('_INSERT_POSITION', "Insert position in list"); /* r1 */
define('_MAKE_DONATION', "Support the Lanius CMS Project with a small donation"); /* r459 */
define('_MAKE_DONATION_ALT', "Lanius CMS Project donation from website"); /* r459 */
define('_SUBMITTED', "Submitted"); /* r462 */
define('_UPLOAD_NONE_SELECTED', "No file selected"); /* r493 */
define('_UI_NO_ROWS', "No data rows"); /* r542 */
define('_OWNER', "Owner"); /* r579 */
define('_TOTAL_HITS', "Total hits"); /* r964 */
?>