<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DBS_SUGGESTION', "If you do not have a professional database management system like MySQL or SQLite, you are invited to use Gladius DB which is the default flatfile database management system."); /* r1 */
define('_DBS_LEGEND', "Legend of combo box items:"); /* r1 */
define('_DBS_GREEN_ITEMS', "Green items"); /* r1 */
define('_DBS_GREEN_ITEMS_DESC', "for database systems currently available"); /* r1 */
define('_DBS_GRAY_ITEMS', "Gray items"); /* r1 */
define('_DBS_ADODB_PACKAGE', "additional adoDB lite driver"); /* r1 */
define('_DBS_GRAY_ITEMS_DESC', "for database systems available on the current PHP installation but not packed with the current Lanius CMS (you would just need to add the relative %s to this installation package)"); /* r1, sprintf */
define('_DBS_RED_ITEMS', "Red items"); /* r1 */
define('_DBS_MODIFY_PHP', "modify the PHP installation"); /* r1 */
define('_DBS_RED_ITEMS_DESC', "for database systems not available on the current PHP installation (you would need to %s)"); /* r1, sprintf */
define('_DBS_SYSTEM', "Database management system"); /* r1 */
define('_DBS_HOST', "Database hostname"); /* r1 */
define('_DBS_USER', "Database username"); /* r1 */
define('_DBS_PASSWORD', "Database password"); /* r1 */
define('_DBS_DBNAME', "Database name"); /* r1 */
define('_DBS_TABLENAME', "tablename"); /* r1 */
define('_DBS_PREFIX', "Database tables prefix"); /* r1 */
define('_DBS_NOT_MANDATORY', "minimal settings required by Gladius DB"); /* r1 */
define('_DBS_MOVE_DB', "Move database (if main settings have changed)"); /* r1 */
define('_DBS_PREFIX_DESC', "Multiple Lanius CMS installations can share the same database settings if a different table prefix is specified for each one."); /* r1 */
?>