<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_AUTH_LDAP_SERVER', "LDAP server"); /* r1 */
define('_AUTH_LDAP_PORT', "LDAP server port"); /* r1 */
define('_AUTH_LDAP_BASE_DN', "LDAP base DN"); /* r1 */
define('_AUTH_LDAP_BIND_DN', "LDAP bind DN"); /* r160 */
define('_AUTH_LDAP_BIND_PASSWORD', "LDAP bind password"); /* r160 */
define('_AUTH_LDAP_ORGANIZATION', "LDAP required organization"); /* r160 */
define('_AUTH_LDAP_ROLE_FIELD', "LDAP required role field"); /* r160 */
define('_AUTH_LDAP_ROLE', "LDAP required role"); /* r160 */
define('_AUTH_LDAP_UID_FIELD', "LDAP unique ID field"); /* r160 */
?>