<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_CTMAILCLOAK_OBFUSCATE_PUNCT', "Obfuscate email punctuation"); /* r1 */
define('_CTMAILCLOAK_USE_HTML', "Use complex HTML"); /* r1 */
define('_CTMAILCLOAK_USE_JAVASCRIPT', "Use javascript"); /* r1 */
define('_CTMAILCLOAK_METHOD', "Cloaking method"); /* r1 */
?>