<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_DRACOM_COMMENTS_LIST', "Posted comments"); /* r1 */
define('_DRACOM_COMMENTS', " Comments"); /* r1 */
define('_DRACOM_COMMENT', " Comment"); /* r1 */
define('_DRACOM_POSTED_BY', "Posted by "); /* r1 */
define('_DRACOM_POSTED_ON', "on"); /* r1 */
define('_DRACOM_YOUR_NAME', "Your name "); /* r1 */
define('_DRACOM_YOUR_COMMENT', "Your comment "); /* r1 */
define('_DRACOM_ADD_COMMENT', "Add comment "); /* r1 */
define('_DRACOM_VIEW', " View, "); /* r1 */
define('_DRACOM_VIEWS', " Views, "); /* r1 */
define('_DRACOM_LAST', " (Last 10 comments shown)"); /* r1 */
define('_DRACOM_TEXT_REMAINING', "Text remaining "); /* r1 */
define('_DRACOM_VISIBILITY', "Comments are visible to"); /* r1 */
define('_DRACOM_APPROVE', "Comments needs approval before being published"); /* r1 */
define('_DRACOM_PRIVATE', "Comments can be marked as private upon submission"); /* r1 */
define('_DRACOM_CAPTCHA', "Enable CAPTCHA test for user less privileged than"); /* r996 */
define('_DRACOM_COMMENT_PENDING', "Your comment has been received and is pending review. Thanks for your submission."); /* r1026 */
define('_DRACOM_COMMENT_OK', "Your comment has been received and successfully published. Thanks for your submission."); /* r1026 */
?>