<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FCKEDITOR_SKIN', "Skin"); /* r160 */
define('_FCKEDITOR_DEFAULT_SKIN', "Default"); /* r160 */
define('_FCKEDITOR_SILVER_SKIN', "Silver"); /* r160 */
define('_FCKEDITOR_OFFICE2003_SKIN', "Office 2003"); /* r160 */
?>