<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_FILE_LOG_LOGFILE', "Directory of log files"); /* r1007 */
define('_FILE_LOG_SPLITSIZE', "Split and rotate log file when reaching this number of bytes"); /* r1007 */
?>