<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_MSG_OPTIONS_ALLOW', "Allow other users to send messages to me (email will not be visible to them)"); /* r423 */
define('_MSG_OPTIONS_ATTACH', "Receive also attachments"); /* r423 */
define('_MSG_OPTIONS_ALLOW_HTML', "Can receive HTML emails"); /* r538 */
define('_MSG_NEW', "%d new messages"); /* r542, sprintf */
define('_MSG_DEFAULT_INSTANCE', "Default message component instance for new messages link"); /* r542 */
?>