<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_REG_FILTER_DOMAINS', "Specify domains (without extension e.g. .com .org .net) to block"); /* r170 */
define('_REG_FILTER_DOMAINS_DESC', "Some email providers do not correctly implement internet protocols and would cause the CMS sent emails to be marked as spam."); /* r170 */
define('_REG_FILTER_INVALID_EMAIL', "You have specified an invalid email address %s.\nEmails would not be correctly sent to this address and would be rejected as spam, because of the broken implementation of those email providers.\nSee also %s."); /* r170, sprintf */
?>