<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_REG_LDAP_CUSTOM_ATTRS', "Custom attributes (e.g. attrname=value) separated by newlines"); /* r160 */
define('_REG_LDAP_DN_FORMAT', "Format string for LDAP creation DN, must contain '%s'"); /* r160 */
define('_REG_LDAP_BIND_DN', "LDAP bind DN for user add"); /* r160 */
define('_REG_LDAP_BIND_PASSWORD', "LDAP bind password for user add"); /* r160 */
?>