<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SMMAIL_SENDMAIL_PATH', "sendmail binary path (without -t,-o,-i,-f options, see also Information -> PHP Info -> sendmail_path)"); /* r561 */
?>