<?php /* DKLANG v0.1 format - saved with Lanius CMS v0.5.0 RC9 (SVN) */
// DO NOT edit this file manually, see http://wiki.laniuscms.org/index.php/Administration/System/Languages_manager
define('_SMTP_SERVER', "SMTP servers (e.g. host1;host2:25)"); /* r1 */
define('_SMTP_FROM', "SMTP MAIL FROM email address override"); /* r1 */
define('_SMTP_PORT', "SMTP server port"); /* r1 */
define('_SMTP_AUTH_USER', "SMTP authentication username (leave empty if no authentication is required)"); /* r1 */
define('_SMTP_AUTH_PASSWORD', "SMTP authentication password"); /* r1 */
define('_SMTP_DEBUG_LEVEL', "Debug level (1 = minimum verbosity, 5 = maximum verbosity)"); /* r664 */
?>